// js/app-export.js — Export engines (PDF, XML, CMSMTF, Text/CSV)
// Extracted from index.html during Phase 2 monolith decomposition
'use strict';

Object.assign(App, {
    async exportPDF() {
        const result = await this.buildPDF(this.data);
        this.downloadBlob(result.blob, result.filename);
        this.logExport('PDF', result.filename);
        this.toast('✓ PDF downloaded successfully');
    },

    exportText() {
        const result = this.buildText(this.data);
        this.downloadFile(result.content, result.filename, result.mime);
        this.logExport('Text', result.filename);
        this.toast('📝 Text summary downloaded');
    },

    async buildPDF(data) {
        const { jsPDF } = window.jspdf;
        const doc = new jsPDF();
        const pageW = doc.internal.pageSize.getWidth();
        const pageH = doc.internal.pageSize.getHeight();
        const margin = 14;
        const contentW = pageW - margin * 2;
        let pageNum = 1;

        // Helper: get value from data, falling back to the current DOM
        // element value. This ensures fields with HTML default values
        // (e.g. numStories="1", bedrooms="3") appear even if the user
        // never manually changed them.
        const v = (key) => {
            if (data[key] !== undefined && data[key] !== null && String(data[key]).trim() !== '') {
                return String(data[key]);
            }
            const el = document.getElementById(key);
            if (el) {
                const val = el.type === 'checkbox' ? (el.checked ? 'Yes' : '') : (el.value || '');
                return val.trim();
            }
            return '';
        };

        // ─── Color palette ───
        const C = {
            brand:    [0, 102, 204],     // Professional blue
            brandLt:  [230, 241, 252],   // Light blue tint
            dark:     [33, 37, 41],       // Near-black text
            mid:      [108, 117, 125],    // Secondary text
            light:    [206, 212, 218],    // Borders
            stripe:   [245, 247, 250],    // Alternating rows
            white:    [255, 255, 255],
            accent:   [40, 167, 69],      // Green accent
            warn:     [220, 53, 69],      // Red accent
        };

        const formatDate = (value) => {
            if (!value) return '';
            const d = new Date(value);
            if (Number.isNaN(d.getTime())) return value;
            return `${String(d.getMonth() + 1).padStart(2, '0')}/${String(d.getDate()).padStart(2, '0')}/${d.getFullYear()}`;
        };
        const formatCurrency = (v) => {
            if (!v) return '';
            const num = parseFloat(String(v).replace(/[$,\s]/g, ''));
            if (isNaN(num)) return v;
            return '$' + num.toLocaleString('en-US');
        };
        const formatDateTime = (value) => {
            const d = value instanceof Date ? value : new Date(value);
            if (Number.isNaN(d.getTime())) return '';
            let hours = d.getHours();
            const minutes = String(d.getMinutes()).padStart(2, '0');
            const ampm = hours >= 12 ? 'PM' : 'AM';
            hours = hours % 12 || 12;
            return `${formatDate(d)} ${hours}:${minutes} ${ampm}`;
        };

        // ─── Layout helpers ───
        let y = 0;

        const checkPage = (needed = 20) => {
            if (y + needed > pageH - 20) {
                doc.addPage();
                pageNum++;
                y = 20;
                return true;
            }
            return false;
        };

        const drawFooter = () => {
            const total = doc.internal.getNumberOfPages();
            for (let i = 1; i <= total; i++) {
                doc.setPage(i);
                doc.setFontSize(7);
                doc.setTextColor(...C.mid);
                doc.text(`Page ${i} of ${total}`, pageW / 2, pageH - 8, { align: 'center' });
                doc.setDrawColor(...C.light);
                doc.setLineWidth(0.3);
                doc.line(margin, pageH - 14, pageW - margin, pageH - 14);
                doc.text('Generated by Altech Insurance Tools', margin, pageH - 8);
                doc.text(formatDateTime(new Date()), pageW - margin, pageH - 8, { align: 'right' });
            }
        };

        const sectionHeader = (title) => {
            checkPage(16);
            doc.setFillColor(...C.brand);
            doc.roundedRect(margin, y, contentW, 7.5, 1.5, 1.5, 'F');
            doc.setFontSize(8);
            doc.setFont(undefined, 'bold');
            doc.setTextColor(...C.white);
            doc.text(title.toUpperCase(), margin + 4, y + 5.3);
            doc.setFont(undefined, 'normal');
            doc.setTextColor(...C.dark);
            y += 10;
        };

        // Key-value rows in a two-column table style
        const kvTable = (fields, cols = 2) => {
            const filtered = fields.filter(([, v]) => v && String(v).trim());
            if (!filtered.length) return;
            const colW = contentW / cols;
            const rowH = 6;
            let rowIdx = 0;
            let col = 0;
            const startY = y;

            filtered.forEach(([label, value], i) => {
                if (col === 0) checkPage(rowH + 2);
                const cellX = margin + col * colW;
                const cellY = y;

                // Alternating stripe (per visual row, not per item)
                if (col === 0 && rowIdx % 2 === 0) {
                    doc.setFillColor(...C.stripe);
                    doc.rect(margin, cellY - 1, contentW, rowH, 'F');
                }

                // Label
                doc.setFontSize(8);
                doc.setFont(undefined, 'bold');
                doc.setTextColor(...C.mid);
                doc.text(label, cellX + 2, cellY + 3.5);

                // Value
                doc.setFont(undefined, 'normal');
                doc.setTextColor(...C.dark);
                const valX = cellX + colW * 0.45;
                const maxValW = colW * 0.52;
                const valLines = doc.splitTextToSize(String(value), maxValW);
                doc.text(valLines[0] || '', valX, cellY + 3.5);

                col++;
                if (col >= cols) {
                    col = 0;
                    y += rowH;
                    rowIdx++;
                }
            });
            if (col > 0) { y += rowH; }

            // Bottom border line
            doc.setDrawColor(...C.light);
            doc.setLineWidth(0.2);
            doc.line(margin, y, margin + contentW, y);
            y += 5;
        };

        // Single-column table for longer content (drivers/vehicles)
        const detailTable = (fields) => {
            const filtered = fields.filter(([, v]) => v && String(v).trim());
            if (!filtered.length) return;
            const rowH = 5.5;
            const labelW = 50;

            filtered.forEach(([label, value], i) => {
                checkPage(rowH + 2);
                const isHeader = !label.startsWith('  ');

                if (isHeader) {
                    // Driver/Vehicle heading row
                    if (i > 0) y += 2;
                    doc.setFillColor(...C.brandLt);
                    doc.rect(margin, y - 1, contentW, rowH + 1, 'F');
                    doc.setFontSize(9);
                    doc.setFont(undefined, 'bold');
                    doc.setTextColor(...C.brand);
                    doc.text(label, margin + 3, y + 3);
                    doc.text(String(value), margin + labelW, y + 3);
                    doc.setFont(undefined, 'normal');
                    doc.setTextColor(...C.dark);
                } else {
                    // Detail sub-row
                    if (i % 2 === 0) {
                        doc.setFillColor(...C.stripe);
                        doc.rect(margin, y - 1, contentW, rowH, 'F');
                    }
                    doc.setFontSize(8);
                    doc.setFont(undefined, 'normal');
                    doc.setTextColor(...C.mid);
                    doc.text(label.trim(), margin + 8, y + 3);
                    doc.setTextColor(...C.dark);
                    doc.text(String(value), margin + labelW, y + 3);
                }
                y += rowH;
            });
            doc.setDrawColor(...C.light);
            doc.setLineWidth(0.2);
            doc.line(margin, y, margin + contentW, y);
            y += 5;
        };

        // ═══════════════════════════════════════
        //  PAGE 1: HEADER
        // ═══════════════════════════════════════
        const address = this.getFullAddress(data);
        const [mapImages, logoImg] = await Promise.all([
            this.getMapImages(address),
            this.fetchImageDataUrl('Resources/altech-logo.png')
        ]);
        const prefix = v('prefix');
        const suffix = v('suffix');
        const nameParts = [prefix, data.firstName || '', data.lastName || '', suffix].filter(Boolean);
        const clientName = nameParts.join(' ') || 'Client';

        // Top accent bar
        doc.setFillColor(...C.brand);
        doc.rect(0, 0, pageW, 3, 'F');
        y = 10;

        // Logo + title header row
        const logoSize = 18;
        let headerTextX = margin;
        if (logoImg?.dataUrl) {
            doc.addImage(logoImg.dataUrl, logoImg.format, margin, y - 2, logoSize, logoSize);
            headerTextX = margin + logoSize + 4;
        }
        doc.setFontSize(14);
        doc.setFont(undefined, 'bold');
        doc.setTextColor(...C.dark);
        doc.text('Altech Insurance', headerTextX, y + 4);
        doc.setFontSize(7.5);
        doc.setFont(undefined, 'normal');
        doc.setTextColor(...C.mid);
        doc.text('Insurance Application Summary', headerTextX, y + 9.5);

        // Document ref & date (right-aligned)
        const docRef = `APP-${new Date().getFullYear()}-${String(new Date().getMonth()+1).padStart(2,'0')}${String(new Date().getDate()).padStart(2,'0')}-${String(Math.floor(Math.random()*9000)+1000)}`;
        doc.setFontSize(7);
        doc.setTextColor(...C.mid);
        doc.text(docRef, pageW - margin, y + 4, { align: 'right' });
        doc.text(formatDateTime(new Date()), pageW - margin, y + 9, { align: 'right' });
        doc.setTextColor(...C.dark);

        y += Math.max(logoSize, 12) + 4;

        // Thin rule under header
        doc.setDrawColor(...C.brand);
        doc.setLineWidth(0.5);
        doc.line(margin, y, pageW - margin, y);
        y += 5;

        // Street View banner (clean — no overlay text)
        if (mapImages?.streetView?.dataUrl) {
            const bannerH = 46;
            doc.addImage(mapImages.streetView.dataUrl, mapImages.streetView.format, margin, y, contentW, bannerH);
            doc.setDrawColor(...C.light);
            doc.setLineWidth(0.3);
            doc.rect(margin, y, contentW, bannerH, 'S');
            y += bannerH + 2;
        }

        // Client info strip
        doc.setFillColor(...C.brandLt);
        doc.rect(margin, y, contentW, 13, 'F');
        doc.setFontSize(12);
        doc.setFont(undefined, 'bold');
        doc.setTextColor(...C.brand);
        doc.text(clientName, margin + 3, y + 5.5);
        doc.setFontSize(7.5);
        doc.setFont(undefined, 'normal');
        doc.setTextColor(...C.mid);
        doc.text(address || '', margin + 3, y + 10.5);
        doc.setTextColor(...C.dark);
        y += 16;

        // Satellite thumbnail
        if (mapImages?.satellite?.dataUrl) {
            const satX = pageW - margin - 30;
            doc.addImage(mapImages.satellite.dataUrl, mapImages.satellite.format, satX, y, 30, 24);
            doc.setDrawColor(...C.light);
            doc.setLineWidth(0.3);
            doc.rect(satX, y, 30, 24, 'S');
            doc.setFontSize(5.5);
            doc.setTextColor(...C.brand);
            const mapUrl = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address || '')}`;
            doc.textWithLink('View on Maps', satX + 15, y + 27, { url: mapUrl, align: 'center' });
            doc.setTextColor(...C.dark);
        }

        // ═══════════════════════════════════════
        //  DATA SECTIONS
        // ═══════════════════════════════════════
        const quoteType = (data.qType || '').toLowerCase();
        const showHome = quoteType === 'home' || quoteType === 'both' || !quoteType;
        const showAuto = quoteType === 'auto' || quoteType === 'both' || !quoteType;
        const drivers = (data.drivers && data.drivers.length) ? data.drivers : (this.drivers || []);
        const vehicles = (data.vehicles && data.vehicles.length) ? data.vehicles : (this.vehicles || []);

        // ── Applicant ──
        sectionHeader('Applicant');
        kvTable([
            ['Full Name', clientName],
            ['Date of Birth', formatDate(v('dob'))],
            ['Gender', v('gender') === 'M' ? 'Male' : v('gender') === 'F' ? 'Female' : v('gender')],
            ['Marital Status', v('maritalStatus')],
            ['Phone', v('phone')],
            ['Email', v('email')],
            ['Education', v('education')],
            ['Industry', v('industry')],
            ['Occupation', v('occupation')],
            ['Quote Type', quoteType === 'home' ? 'Home Only' : quoteType === 'auto' ? 'Auto Only' : quoteType === 'both' ? 'Home & Auto' : quoteType],
            ['Pronunciation', this.getNamePronunciation(data)],
        ]);

        // ── Co-Applicant (if provided) ──
        if (data.hasCoApplicant === 'yes' && (data.coFirstName || data.coLastName)) {
            sectionHeader('Co-Applicant / Spouse');
            kvTable([
                ['Full Name', `${data.coFirstName || ''} ${data.coLastName || ''}`.trim()],
                ['Date of Birth', formatDate(v('coDob'))],
                ['Gender', v('coGender') === 'M' ? 'Male' : v('coGender') === 'F' ? 'Female' : v('coGender')],
                ['Email', v('coEmail')],
                ['Phone', v('coPhone')],
                ['Relationship', v('coRelationship')],
            ]);
        }

        // ── Property Address ──
        sectionHeader('Property Address');
        kvTable([
            ['Street Address', v('addrStreet')],
            ['City', v('addrCity')],
            ['State', v('addrState')],
            ['ZIP Code', v('addrZip')],
            ['County', this.getCountyFromCity(data.addrCity, data.addrState) || ''],
            ['Years at Address', v('yearsAtAddress')],
        ]);

        if (showHome) {
            // ── Property Details ──
            sectionHeader('Property Details');
            kvTable([
                ['Year Built', v('yrBuilt')],
                ['Square Footage', v('sqFt') ? Number(v('sqFt')).toLocaleString() + ' sq ft' : ''],
                ['Lot Size', v('lotSize') ? v('lotSize') + ' acres' : ''],
                ['Dwelling Type', v('dwellingType')],
                ['Dwelling Use', v('dwellingUsage')],
                ['Occupancy', v('occupancyType')],
                ['Stories', v('numStories')],
                ['Occupants', v('numOccupants')],
                ['Bedrooms', v('bedrooms')],
                ['Full Baths', v('fullBaths')],
                ['Half Baths', v('halfBaths')],
                ['Construction', v('constructionStyle')],
                ['Exterior Walls', v('exteriorWalls')],
                ['Foundation', v('foundation')],
                ['Garage Type', v('garageType')],
                ['Garage Spaces', v('garageSpaces')],
                ['Kitchen/Bath Quality', v('kitchenQuality')],
                ['Flooring', v('flooring')],
                ['Fireplaces', v('numFireplaces')],
                ['Purchase Date', formatDate(v('purchaseDate'))],
            ]);

            // ── Building Systems ──
            sectionHeader('Building Systems');
            kvTable([
                ['Roof Type', v('roofType')],
                ['Roof Shape', v('roofShape')],
                ['Roof Updated', v('roofYr')],
                ['Heating Type', v('heatingType')],
                ['Heating Updated', v('heatYr')],
                ['Cooling', v('cooling')],
                ['Plumbing Updated', v('plumbYr')],
                ['Electrical Updated', v('elecYr')],
                ['Sewer', v('sewer')],
                ['Water Source', v('waterSource')],
            ]);

            // ── Risk & Protection ──
            sectionHeader('Risk & Protection');
            kvTable([
                ['Burglar Alarm', v('burglarAlarm')],
                ['Fire Alarm', v('fireAlarm')],
                ['Smoke Detector', v('smokeDetector')],
                ['Sprinklers', v('sprinklers')],
                ['Swimming Pool', v('pool') || 'No'],
                ['Trampoline', v('trampoline') || 'No'],
                ['Wood Stove', v('woodStove') && v('woodStove') !== 'None' ? v('woodStove') : 'None'],
                ['Secondary Heating', v('secondaryHeating')],
                ['Dog on Premises', data.dogInfo || 'None'],
                ['Business on Property', data.businessOnProperty || 'No'],
                ['Fire Station (mi)', v('fireStationDist')],
                ['Fire Hydrant (ft)', v('fireHydrantFeet')],
                ['Tidal Water (ft)', v('tidalWaterDist')],
                ['Protection Class', v('protectionClass')],
            ]);

            // ── Home Coverage ──
            sectionHeader('Home Coverage');
            kvTable([
                ['Policy Type', v('homePolicyType')],
                ['Dwelling Coverage', formatCurrency(v('dwellingCoverage'))],
                ['Personal Liability', formatCurrency(v('personalLiability'))],
                ['Medical Payments', formatCurrency(v('medicalPayments'))],
                ['Deductible', formatCurrency(v('homeDeductible'))],
                ['Wind/Hail Ded.', formatCurrency(v('windDeductible'))],
                ['Mortgagee', v('mortgagee')],
                ['Increased Repl. Cost', v('increasedReplacementCost')],
                ['Ordinance or Law', v('ordinanceOrLaw')],
                ['Water Backup', v('waterBackup')],
                ['Loss Assessment', formatCurrency(v('lossAssessment'))],
                ['Equipment Breakdown', v('equipmentBreakdown')],
                ['Service Line', v('serviceLine')],
                ['Animal Liability', formatCurrency(v('animalLiability'))],
                ['Earthquake Coverage', v('earthquakeCoverage')],
            ]);
        }

        if (showAuto) {
            // ── Drivers ──
            if (drivers.length) {
                sectionHeader('Drivers');
                const driverRows = drivers.map((d, i) => {
                    const name = [d.firstName, d.lastName].filter(Boolean).join(' ');
                    return [
                        [`Driver ${i + 1}`, name || 'Unknown'],
                        ['  Date of Birth', formatDate(d.dob || '')],
                        ['  Gender', d.gender === 'M' ? 'Male' : d.gender === 'F' ? 'Female' : (d.gender || '')],
                        ['  Marital Status', d.maritalStatus || ''],
                        ['  Relationship', d.relationship || ''],
                        ['  Education', d.education || ''],
                        ['  Occupation', d.occupation || ''],
                        ['  License #', (d.dlNum || '').toUpperCase()],
                        ['  License State', (d.dlState || '').toUpperCase()],
                    ];
                }).flat();
                detailTable(driverRows);
            }

            // ── Vehicles ──
            if (vehicles.length) {
                sectionHeader('Vehicles');
                const vehicleRows = vehicles.map((v, i) => {
                    const vehDesc = [v.year, v.make, v.model].filter(Boolean).join(' ');
                    const driverDisplay = this.resolveDriverName(v.primaryDriver, drivers);
                    return [
                        [`Vehicle ${i + 1}`, vehDesc || 'Unknown'],
                        ['  VIN', v.vin || ''],
                        ['  Usage', v.use || ''],
                        ['  Annual Miles', v.miles ? Number(v.miles).toLocaleString() : ''],
                        ['  Primary Driver', driverDisplay],
                    ];
                }).flat();
                detailTable(vehicleRows);
            }

            // Legacy single-vehicle (if no multi-vehicle data)
            if (!vehicles.length && (data.vehDesc || data.vin)) {
                sectionHeader('Vehicle');
                kvTable([
                    ['Vehicle', data.vehDesc || ''],
                    ['VIN', data.vin || ''],
                    ['Usage', data.use || ''],
                    ['Annual Miles', data.miles || ''],
                ]);
            }

            // ── Auto Coverage ──
            sectionHeader('Auto Coverage');
            kvTable([
                ['Auto Policy Type', v('autoPolicyType')],
                ['Residence Is', v('residenceIs')],
                ['Liability Limits', v('liabilityLimits')],
                ['Property Damage', v('pdLimit')],
                ['Med Pay (Auto)', formatCurrency(v('medPayments'))],
                ['UM Limits', v('umLimits')],
                ['UIM Limits', v('uimLimits')],
                ['UMPD Limit', v('umpdLimit')],
                ['Comprehensive Ded.', formatCurrency(v('compDeductible'))],
                ['Collision Ded.', formatCurrency(v('autoDeductible'))],
                ['Rental Reimburse.', v('rentalDeductible')],
                ['Towing/Roadside', v('towingDeductible')],
                ['Student GPA', v('studentGPA')],
            ]);
        }

        // ── Policy & Prior Insurance ──
        sectionHeader('Policy & Prior Insurance');
        const pdfPriorRows = [
            ['Policy Term', v('policyTerm')],
            ['Effective Date', formatDate(v('effectiveDate'))],
        ];
        if (showHome) {
            const hCarrier = v('homePriorCarrier') || v('priorCarrier');
            pdfPriorRows.push(
                ['Home Prior Carrier', hCarrier],
                ['Home Prior Term', v('homePriorPolicyTerm') || v('priorPolicyTerm')],
                ['Home Yrs w/ Prior', v('homePriorYears') || v('priorYears')],
                ['Home Prior Exp.', formatDate(v('homePriorExp') || v('priorExp'))]
            );
        }
        if (showAuto) {
            pdfPriorRows.push(
                ['Auto Prior Carrier', v('priorCarrier')],
                ['Auto Prior Term', v('priorPolicyTerm')],
                ['Auto Yrs w/ Prior', v('priorYears')],
                ['Auto Prior Exp.', formatDate(v('priorExp'))]
            );
        }
        pdfPriorRows.push(
            ['Continuous Coverage', v('continuousCoverage')],
            ['Accidents', v('accidents')],
            ['Violations', v('violations')]
        );
        kvTable(pdfPriorRows);

        // ── Additional Information ──
        sectionHeader('Additional Information');
        kvTable([
            ['Additional Insureds', v('additionalInsureds')],
            ['Best Contact Time', v('contactTime')],
            ['Contact Method', v('contactMethod')],
            ['Referral Source', v('referralSource')],
            ['TCPA Consent', data.tcpaConsent ? 'Yes' : 'No'],
        ], 2);

        // ─── Footer on every page ───
        drawFooter();

        const fileName = `Insurance_Application_${data.lastName || 'Client'}_${new Date().toISOString().split('T')[0]}.pdf`;
        return { blob: doc.output('blob'), filename: fileName };
    },

    buildText(data) {
        const content = this.getNotesForData(data);
        const fileName = `Insurance_Application_${data.lastName || 'Client'}_${new Date().toISOString().split('T')[0]}.txt`;
        return { content, filename: fileName, mime: 'text/plain;charset=utf-8' };
    },

    exportCSV() {
        const result = this.buildCSV(this.data);
        this.downloadFile(result.content, result.filename, result.mime);
        this.logExport('CSV', result.filename);
        this.toast('📥 CSV Generated!');
    },

    buildCSV(data) {
        const h = this.getCSVHeaders();
        const flatNotes = this.getNotesForData(data).replace(/\n/g, ' | ');
        const driversSummary = (data.drivers || []).map((d, i) => {
            const name = [d.firstName, d.lastName].filter(Boolean).join(' ');
            return `Driver ${i + 1}: ${name || 'Unknown'} (${d.occupation || 'N/A'})`;
        }).join(' | ');
        const row = [
            data.firstName, data.lastName, data.addrStreet, data.addrCity, data.addrState, data.addrZip,
            data.phone, data.email, data.dob, flatNotes, data.qType, driversSummary
        ].map(v => `"${v||''}"`).join(',');

        const csv = h.join(',') + "\n" + row;
        return { content: csv, filename: `Lead_${data.lastName || 'Export'}.csv`, mime: 'text/csv' };
    },

    getCSVHeaders() {
        return ["First Name","Last Name","Address Line 1","City","State Code","Zip Code","Mobile Phone","Email","Date of Birth","Notes","Quote Type","Drivers/Occupations"];
    },

    downloadCSVTemplate() {
        const headers = this.getCSVHeaders();
        const sample = [
            'Jane','Doe','123 Main St','Seattle','WA','98101','2065551212','jane@example.com','1985-05-12','Follow up','home','Driver 1: Jane Doe (Engineer)'
        ].map(v => `"${v}"`).join(',');
        const content = `${headers.join(',')}\n${sample}`;
        this.downloadFile(content, 'Altech_Batch_Template.csv', 'text/csv');
        this.toast('📄 CSV template downloaded');
    },

    openBatchImport() {
        const input = document.getElementById('batchCsvInput');
        if (!input) return;
        input.value = '';
        input.click();
    },

    async handleBatchImport(file) {
        if (!file) return;
        const text = await file.text();
        const parsed = this.parseCSV(text);
        if (!parsed || !parsed.rows.length) {
            this.toast('⚠️ CSV has no rows.');
            return;
        }

        const quotes = await this.getQuotes();
        const errors = [];
        let created = 0;

        parsed.rows.forEach((row, index) => {
            const data = this.mapCsvRowToData(parsed.headers, row);
            if (!data.addrStreet || !data.addrCity || !data.addrState) {
                errors.push(`Row ${index + 2}: Missing address fields`);
                return;
            }

            const id = `${Date.now()}_${Math.random().toString(36).slice(2,8)}`;
            const title = this.getQuoteTitle(data);
            quotes.unshift({
                id,
                title,
                data,
                updatedAt: new Date().toISOString(),
                starred: false,
                isDuplicate: false
            });
            created += 1;
        });

        await this.saveQuotes(quotes);
        await this.renderQuoteList();

        if (created) {
            this.toast(`✅ Imported ${created} draft${created > 1 ? 's' : ''}`);
        }
        if (errors.length) {
            console.warn('Batch import warnings:', errors);
            this.toast('⚠️ Some rows were skipped.');
        }
    },

    parseCSV(text) {
        if (!text) return { headers: [], rows: [] };
        const rows = [];
        let cur = '';
        let row = [];
        let inQuotes = false;

        for (let i = 0; i < text.length; i++) {
            const ch = text[i];
            const next = text[i + 1];

            if (ch === '"') {
                if (inQuotes && next === '"') {
                    cur += '"';
                    i++;
                } else {
                    inQuotes = !inQuotes;
                }
                continue;
            }

            if (ch === ',' && !inQuotes) {
                row.push(cur);
                cur = '';
                continue;
            }

            if ((ch === '\n' || ch === '\r') && !inQuotes) {
                if (ch === '\r' && next === '\n') i++;
                row.push(cur);
                cur = '';
                if (row.some(cell => cell.trim().length)) {
                    rows.push(row);
                }
                row = [];
                continue;
            }

            cur += ch;
        }

        if (cur.length || row.length) {
            row.push(cur);
            if (row.some(cell => cell.trim().length)) {
                rows.push(row);
            }
        }

        const headers = (rows.shift() || []).map(h => h.trim());
        return { headers, rows };
    },

    mapCsvRowToData(headers, row) {
        const data = {};
        headers.forEach((header, i) => {
            const key = header.toLowerCase().replace(/[^a-z0-9]/g, '');
            const value = (row[i] || '').trim();

            const map = {
                firstname: 'firstName',
                lastname: 'lastName',
                addressline1: 'addrStreet',
                city: 'addrCity',
                statecode: 'addrState',
                zipcode: 'addrZip',
                mobilephone: 'phone',
                email: 'email',
                dateofbirth: 'dob',
                notes: 'importNotes',
                quotetype: 'qType'
            };

            const field = map[key];
            if (field) data[field] = value;
        });

        if (data.addrState) data.addrState = data.addrState.toUpperCase();
        if (data.qType) {
            const qt = data.qType.toLowerCase();
            if (['home','auto','both'].includes(qt)) data.qType = qt;
        }
        return data;
    },

    exportCMSMTF() {
        const result = this.buildCMSMTF(this.data);
        this.downloadFile(result.content, result.filename, result.mime);
        this.logExport('CMSMTF', result.filename);
        this.toast('📥 HawkSoft File Generated!');
    },

    buildCMSMTF(data) {
        const qType = data.qType || 'both';
        const includeHome = qType === 'home' || qType === 'both';
        const includeAuto = qType === 'auto' || qType === 'both';
        
        const fields = [
            // ── Core Contact ──
            { tag: 'NAM', value: `${data.firstName || ''} ${data.lastName || ''}`.trim() },
            { tag: 'ADD', value: data.addrStreet },
            { tag: 'CTY', value: data.addrCity },
            { tag: 'STA', value: data.addrState },
            { tag: 'ZIP', value: data.addrZip },
            { tag: 'PHN', value: data.phone ? data.phone.replace(/\D/g, '') : '' },
            { tag: 'EML', value: data.email },
            { tag: 'DOB', value: this.formatDateDisplay(data.dob) },
            { tag: 'MARITAL_STATUS', value: data.maritalStatus },
            { tag: 'EDUCATION', value: data.education },
            { tag: 'INDUSTRY', value: data.industry },
        ];

        // ── Co-Applicant ──
        if (data.hasCoApplicant === 'yes' && (data.coFirstName || data.coLastName)) {
            fields.push(
                { tag: 'CO_NAM', value: `${data.coFirstName || ''} ${data.coLastName || ''}`.trim() },
                { tag: 'CO_DOB', value: this.formatDateDisplay(data.coDob) },
                { tag: 'CO_GENDER', value: data.coGender },
                { tag: 'CO_EML', value: data.coEmail },
                { tag: 'CO_PHN', value: data.coPhone ? data.coPhone.replace(/\D/g, '') : '' },
                { tag: 'CO_REL', value: data.coRelationship }
            );
        }

        // ── Home/Property (only when quoting home) ──
        if (includeHome) {
            fields.push(
                { tag: 'L1', value: data.roofYr },
                { tag: 'L2', value: data.roofType },
                { tag: 'L3', value: data.heatingType },
                { tag: 'L4', value: data.heatYr },
                { tag: 'L5', value: data.plumbYr },
                { tag: 'L6', value: data.elecYr },
                { tag: 'L7', value: data.pool },
                { tag: 'L8', value: data.dogInfo },
                { tag: 'L9', value: data.kitchenQuality },
                { tag: 'L10', value: data.burglarAlarm },
                { tag: 'DWELLING_TYPE', value: data.dwellingType },
                { tag: 'DWELLING_USAGE', value: data.dwellingUsage },
                { tag: 'YEAR_BUILT', value: data.yrBuilt },
                { tag: 'SQ_FT', value: data.sqFt },
                { tag: 'STORIES', value: data.numStories },
                { tag: 'BATHROOMS', value: data.fullBaths },
                { tag: 'CONSTRUCTION', value: data.constructionStyle },
                { tag: 'EXTERIOR_WALLS', value: data.exteriorWalls },
                { tag: 'FOUNDATION', value: data.foundation },
                { tag: 'ROOF_SHAPE', value: data.roofShape },
                { tag: 'COOLING', value: data.cooling },
                { tag: 'FIRE_ALARM', value: data.fireAlarm },
                { tag: 'SPRINKLERS', value: data.sprinklers },
                { tag: 'PROTECTION_CLASS', value: data.protectionClass },
                { tag: 'R2', value: data.trampoline },
                { tag: 'R3', value: data.woodStove },
                { tag: 'R4', value: data.businessOnProperty },
                { tag: 'R5', value: this.formatDateDisplay(data.purchaseDate) },
                { tag: 'R6', value: data.mortgagee }
            );
        }

        // ── Auto/Vehicle (only when quoting auto) ──
        if (includeAuto) {
            fields.push(
                { tag: 'C1', value: data.liabilityLimits },
                { tag: 'C4', value: data.accidents },
                { tag: 'C5', value: data.violations },
                { tag: 'C6', value: data.miles },
                { tag: 'C7', value: data.commuteDist },
                { tag: 'C8', value: data.rideSharing },
                { tag: 'C9', value: data.telematics },
                { tag: 'C10', value: data.studentGPA },
                { tag: 'VIN', value: data.vin },
                { tag: 'VEH', value: data.vehDesc },
                { tag: 'DL_NUM', value: (data.dlNum || '').toUpperCase() },
                { tag: 'DL_STATE', value: data.dlState },
                { tag: 'VEHICLE_USE', value: data.use }
            );
        }

        // ── Prior Insurance (split by line of business) ──
        if (includeAuto) {
            fields.push(
                { tag: 'C2', value: data.priorCarrier },
                { tag: 'C3', value: data.priorYears }
            );
        }
        if (includeHome) {
            fields.push(
                { tag: 'L_PRIOR_CARRIER', value: data.homePriorCarrier || data.priorCarrier },
                { tag: 'L_PRIOR_YEARS', value: data.homePriorYears || data.priorYears }
            );
        }

        // ── Shared fields ──
        fields.push(
            { tag: 'R1', value: includeHome && includeAuto
                ? `Home: ${data.homeDeductible || ''} / Auto: ${data.autoDeductible || ''}`
                : includeHome ? data.homeDeductible : data.autoDeductible },
            { tag: 'R7', value: data.additionalInsureds },
            { tag: 'R8', value: data.contactTime },
            { tag: 'R9', value: data.referralSource },
            { tag: 'R10', value: data.tcpaConsent ? 'Yes - Consented' : 'No' }
        );

        const content = fields
            .filter(f => f.value && f.value.toString().trim() !== '')
            .map(f => `[${f.tag}]${f.value}`)
            .join('\n');

        return { content, filename: `Lead_${data.lastName || 'Export'}.cmsmtf`, mime: 'text/plain;charset=utf-8' };
    },

    exportXML() {
        const result = this.buildXML(this.data);
        if (!result.ok) {
            this.toast(result.error);
            return;
        }
        this.downloadFile(result.content, result.filename, result.mime);
        this.logExport('XML', result.filename);
        this.toast('📥 EZLynx Auto XML File Generated!');
    },

    updateExportButtons() {
        const qType = (document.querySelector('input[name="qType"]:checked') || {}).value || 'both';
        const autoBtn = document.getElementById('ezlynx-auto-btn');
        const homeBtn = document.getElementById('ezlynx-home-btn');
        const bothBtn = document.getElementById('ezlynx-both-btn');
        if (!autoBtn || !homeBtn || !bothBtn) return;

        if (qType === 'home') {
            autoBtn.style.display = 'none';
            homeBtn.style.display = 'block';
            bothBtn.style.display = 'none';
        } else if (qType === 'auto') {
            autoBtn.style.display = 'block';
            homeBtn.style.display = 'none';
            bothBtn.style.display = 'none';
        } else {
            // 'both'
            autoBtn.style.display = 'block';
            homeBtn.style.display = 'block';
            bothBtn.style.display = 'block';
        }
    },

    launchEZLynxFromExport() {
        // Navigate to EZLynx Quoter tool, auto-load intake data, and launch filler
        this.openTool('ezlynx');
        // Give tool time to render, then load data and launch
        setTimeout(() => {
            if (typeof EZLynxTool !== 'undefined') {
                EZLynxTool.loadFromIntake();
                // Small delay so user can see the loaded data before launching
                setTimeout(() => {
                    EZLynxTool.launch();
                }, 500);
            }
        }, 300);
    },

    async exportBothXML() {
        const autoResult = this.buildXML(this.data);
        const homeResult = this.buildHomeXML(this.data);
        if (!autoResult.ok) {
            this.toast(autoResult.error);
            return;
        }
        if (!homeResult.ok) {
            this.toast(homeResult.error);
            return;
        }
        // Use JSZip to bundle both files
        if (typeof JSZip === 'undefined') {
            // Fallback: download individually
            this.downloadFile(autoResult.content, autoResult.filename, autoResult.mime);
            setTimeout(() => {
                this.downloadFile(homeResult.content, homeResult.filename, homeResult.mime);
            }, 500);
            this.toast('📦 Both XML files downloaded!');
            return;
        }
        const zip = new JSZip();
        zip.file(autoResult.filename, autoResult.content);
        zip.file(homeResult.filename, homeResult.content);
        const lastName = this.data.lastName || 'Lead';
        const blob = await zip.generateAsync({ type: 'blob' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${lastName}_EZLynx_Bundle.zip`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        this.logExport('BothXML', `${lastName}_EZLynx_Bundle.zip`);
        this.toast('📦 Auto + Home XML Bundle Downloaded!');
    },

    // ─── Shared XML Export Helpers ────────────────────────────
    // Used by both buildXML (auto) and buildHomeXML (home)

    _escapeXML(str) {
        if (!str) return '';
        return String(str)
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&apos;');
    },

    // Escape for safe HTML attribute/text content insertion
    _escapeAttr(str) {
        if (!str) return '';
        return String(str)
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&#39;');
    },

    // Shared Gemini scan schema (used by processScan + processScanFromText)
    _getScanSchema() {
        const fieldProps = {
            // Applicant
            prefix: { type: 'string' }, firstName: { type: 'string' }, lastName: { type: 'string' }, suffix: { type: 'string' },
            dob: { type: 'string' }, gender: { type: 'string' }, maritalStatus: { type: 'string' },
            phone: { type: 'string' }, email: { type: 'string' },
            education: { type: 'string' }, occupation: { type: 'string' }, industry: { type: 'string' },
            // Co-Applicant
            coFirstName: { type: 'string' }, coLastName: { type: 'string' },
            coDob: { type: 'string' }, coGender: { type: 'string' }, coEmail: { type: 'string' }, coPhone: { type: 'string' }, coRelationship: { type: 'string' },
            // Address
            addrStreet: { type: 'string' }, addrCity: { type: 'string' },
            addrState: { type: 'string' }, addrZip: { type: 'string' },
            yearsAtAddress: { type: 'string' }, county: { type: 'string' },
            // Property
            dwellingUsage: { type: 'string' }, occupancyType: { type: 'string' },
            yrBuilt: { type: 'string' }, sqFt: { type: 'string' }, dwellingType: { type: 'string' },
            roofType: { type: 'string' }, roofShape: { type: 'string' }, roofYr: { type: 'string' },
            constructionStyle: { type: 'string' },
            numStories: { type: 'string' }, foundation: { type: 'string' },
            exteriorWalls: { type: 'string' }, heatingType: { type: 'string' },
            cooling: { type: 'string' }, heatYr: { type: 'string' },
            plumbYr: { type: 'string' }, elecYr: { type: 'string' },
            sewer: { type: 'string' }, waterSource: { type: 'string' },
            garageType: { type: 'string' }, garageSpaces: { type: 'string' }, lotSize: { type: 'string' },
            numOccupants: { type: 'string' }, bedrooms: { type: 'string' },
            fullBaths: { type: 'string' }, halfBaths: { type: 'string' },
            kitchenQuality: { type: 'string' }, flooring: { type: 'string' },
            numFireplaces: { type: 'string' }, purchaseDate: { type: 'string' },
            pool: { type: 'string' }, trampoline: { type: 'string' }, dogInfo: { type: 'string' },
            businessOnProperty: { type: 'string' }, woodStove: { type: 'string' },
            // Safety & Protection
            burglarAlarm: { type: 'string' }, fireAlarm: { type: 'string' },
            sprinklers: { type: 'string' }, smokeDetector: { type: 'string' },
            fireStationDist: { type: 'string' }, fireHydrantFeet: { type: 'string' }, protectionClass: { type: 'string' },
            // Home Coverage
            homePolicyType: { type: 'string' }, dwellingCoverage: { type: 'string' },
            personalLiability: { type: 'string' }, medicalPayments: { type: 'string' },
            homeDeductible: { type: 'string' }, windDeductible: { type: 'string' }, mortgagee: { type: 'string' },
            // Auto / Vehicles
            vin: { type: 'string' }, vehDesc: { type: 'string' },
            autoPolicyType: { type: 'string' },
            liabilityLimits: { type: 'string' }, pdLimit: { type: 'string' },
            umLimits: { type: 'string' }, uimLimits: { type: 'string' },
            compDeductible: { type: 'string' }, autoDeductible: { type: 'string' },
            medPayments: { type: 'string' },
            rentalDeductible: { type: 'string' }, towingDeductible: { type: 'string' },
            studentGPA: { type: 'string' },
            // Policy / Prior
            policyNumber: { type: 'string' },
            effectiveDate: { type: 'string' }, policyTerm: { type: 'string' },
            priorCarrier: { type: 'string' }, priorExp: { type: 'string' },
            priorPolicyTerm: { type: 'string' }, priorLiabilityLimits: { type: 'string' },
            priorYears: { type: 'string' }, continuousCoverage: { type: 'string' },
            homePriorCarrier: { type: 'string' }, homePriorExp: { type: 'string' },
            homePriorPolicyTerm: { type: 'string' }, homePriorYears: { type: 'string' },
            accidents: { type: 'string' }, violations: { type: 'string' },
            // Additional
            additionalInsureds: { type: 'string' },
            contactTime: { type: 'string' }, referralSource: { type: 'string' },
            additionalVehicles: { type: 'string' }, additionalDrivers: { type: 'string' },
        };
        const confProps = {};
        Object.keys(fieldProps).forEach(k => { confProps[k] = { type: 'number' }; });
        return {
            type: 'object',
            properties: {
                fields: { type: 'object', properties: fieldProps },
                confidence: { type: 'object', properties: confProps },
                quality_issues: { type: 'array', items: { type: 'string' } }
            },
            required: ['fields']
        };
    },

    _mapGender(g) {
        if (g === 'M') return 'Male';
        if (g === 'F') return 'Female';
        return g || '';
    },

    _mapMaritalStatus(m) {
        const valid = ['Single','Married','Divorced','Widowed','Separated','Domestic Partner'];
        if (!m) return '';
        const match = valid.find(v => v.toLowerCase() === m.toLowerCase());
        return match || m;
    },

    _normalizeDate(dateStr) {
        if (!dateStr) return '';
        const d = new Date(dateStr);
        if (Number.isNaN(d.getTime())) return '';
        const year = d.getUTCFullYear();
        if (year < 1900 || year > 2100) return '';
        return d.toISOString().split('T')[0];
    },

    _splitZip(zip) {
        const raw = (zip || '').toString().trim();
        if (!raw) return { zip5: '', zip4: '' };
        const digits = raw.replace(/[^0-9]/g, '');
        if (digits.length >= 9) {
            return { zip5: digits.slice(0, 5), zip4: digits.slice(5, 9) };
        }
        return { zip5: digits.slice(0, 5), zip4: '' };
    },

    buildXML(data) {
        const escapeXML = this._escapeXML;
        const mapGender = this._mapGender;
        const mapMaritalStatus = this._mapMaritalStatus;
        const normalizeDate = this._normalizeDate;
        const splitZip = this._splitZip;

        const parseLimits = (value) => {
            if (!value) return { bi: '', pd: '' };
            const cleaned = String(value).replace(/\s+/g, '');
            const parts = cleaned.split('/').filter(Boolean);
            if (parts.length >= 2) {
                return { bi: `${parts[0]}/${parts[1]}`, pd: parts[2] || '' };
            }
            return { bi: cleaned, pd: '' };
        };

        // Use arrays if available, otherwise fall back to flat fields
        const drivers = (data.drivers && data.drivers.length > 0) ? data.drivers : null;
        const vehicles = (data.vehicles && data.vehicles.length > 0) ? data.vehicles : null;

        // Get primary applicant info (use first driver if array exists, otherwise use flat fields)
        const primaryDriver = drivers ? drivers[0] : data;
        const firstName = primaryDriver.firstName || data.firstName || '';
        const lastName = primaryDriver.lastName || data.lastName || '';
        const dob = normalizeDate(primaryDriver.dob || data.dob);

        // Validation
        if (!firstName || !lastName) {
            return { ok: false, error: '⚠️ First and last name are required for EZLynx XML.' };
        }
        const state = (data.addrState || '').trim().toUpperCase();
        if (!state || !/^[A-Z]{2}$/.test(state)) {
            return { ok: false, error: '⚠️ A valid 2-letter state is required for EZLynx XML.' };
        }
        if (!dob) {
            return { ok: false, error: '⚠️ A valid DOB is required for EZLynx XML.' };
        }

        // VIN is optional for EZLynx XML export, but each vehicle needs VIN or year/make/model
        const isAutoPolicy = data.qType === 'auto' || data.qType === 'both';
        if (isAutoPolicy) {
            if (vehicles && vehicles.length) {
                const invalidVehicles = vehicles.filter(v => {
                    const hasVin = v.vin && v.vin.trim().length > 0;
                    const hasDetails = (v.year && v.make && v.model);
                    return !hasVin && !hasDetails;
                });
                if (invalidVehicles.length) {
                    return { ok: false, error: '⚠️ Each vehicle needs a VIN or Year/Make/Model for EZLynx XML.' };
                }
            } else {
                const hasVin = data.vin && data.vin.trim().length > 0;
                const hasDesc = data.vehDesc && data.vehDesc.trim().length > 0;
                if (!hasVin && !hasDesc) {
                    return { ok: false, error: '⚠️ Add at least one vehicle (VIN or Year/Make/Model) for EZLynx XML.' };
                }
                if (!hasVin && hasDesc) {
                    const match = data.vehDesc.match(/(\d{4})\s+([A-Z]+)\s+(.+)/i);
                    if (!match) {
                        return { ok: false, error: '⚠️ Vehicle description should be "YEAR MAKE MODEL" if no VIN is provided.' };
                    }
                }
            }
        }

        const phone = data.phone ? data.phone.replace(/\D/g, '') : '';
        const streetRaw = (data.addrStreet || '').trim();
        const streetMatch = streetRaw.match(/^(\d+)\s+(.*)$/);
        const streetNumber = streetMatch?.[1] || '';
        const streetName = streetMatch?.[2] || streetRaw;
        const { zip5, zip4 } = splitZip(data.addrZip);
        const gender = mapGender(data.gender);
        const marital = mapMaritalStatus(data.maritalStatus);

        let xml = '<?xml version="1.0" encoding="utf-8"?>\n';
        xml += '<EZAUTO xmlns="http://www.ezlynx.com/XMLSchema/Auto/V200">\n';

        // Applicant section (primary contact info)
        xml += '  <Applicant>\n';
        xml += '    <ApplicantType>Applicant</ApplicantType>\n';
        xml += '    <PersonalInfo>\n';
        xml += '      <Name>\n';
        xml += `        <FirstName>${escapeXML(firstName)}</FirstName>\n`;
        xml += '        <MiddleName></MiddleName>\n';
        xml += `        <LastName>${escapeXML(lastName)}</LastName>\n`;
        xml += '      </Name>\n';
        xml += `      <DOB>${dob}</DOB>\n`;
        if (gender) {
            xml += `      <Gender>${escapeXML(gender)}</Gender>\n`;
        }
        if (marital) {
            xml += `      <MaritalStatus>${escapeXML(marital)}</MaritalStatus>\n`;
        }
        xml += '      <Relation>Insured</Relation>\n';
        xml += '    </PersonalInfo>\n';
        xml += '    <Address>\n';
        xml += '      <AddressCode>StreetAddress</AddressCode>\n';
        xml += '      <Addr1>\n';
        xml += `        <StreetName>${escapeXML(streetName)}</StreetName>\n`;
        xml += `        <StreetNumber>${escapeXML(streetNumber)}</StreetNumber>\n`;
        xml += '      </Addr1>\n';
        xml += `      <City>${escapeXML(data.addrCity)}</City>\n`;
        xml += `      <StateCode>${escapeXML(state)}</StateCode>\n`;
        const county = this.getCountyFromCity(data.addrCity, state);
        if (county) {
            xml += `      <County>${escapeXML(county)}</County>\n`;
        }
        xml += `      <Zip5>${escapeXML(zip5)}</Zip5>\n`;
        if (phone) {
            xml += '      <Phone id="1">\n';
            xml += '        <PhoneType>Mobile</PhoneType>\n';
            xml += `        <PhoneNumber>${escapeXML(phone)}</PhoneNumber>\n`;
            xml += '        <Extension></Extension>\n';
            xml += '      </Phone>\n';
        }
        if (data.email) {
            xml += `      <Email>${escapeXML(data.email)}</Email>\n`;
        }
        xml += '    </Address>\n';
        xml += '  </Applicant>\n';

        // Co-Applicant section (if provided)
        if (data.hasCoApplicant === 'yes' && (data.coFirstName || data.coLastName)) {
            const coDob = normalizeDate(data.coDob);
            const coGender = mapGender(data.coGender);
            xml += '  <Applicant>\n';
            xml += '    <ApplicantType>CoApplicant</ApplicantType>\n';
            xml += '    <PersonalInfo>\n';
            xml += '      <Name>\n';
            xml += `        <FirstName>${escapeXML(data.coFirstName || '')}</FirstName>\n`;
            xml += '        <MiddleName></MiddleName>\n';
            xml += `        <LastName>${escapeXML(data.coLastName || '')}</LastName>\n`;
            xml += '      </Name>\n';
            if (coDob) xml += `      <DOB>${coDob}</DOB>\n`;
            if (coGender) xml += `      <Gender>${escapeXML(coGender)}</Gender>\n`;
            if (marital) xml += `      <MaritalStatus>${escapeXML(marital)}</MaritalStatus>\n`;
            xml += `      <Relation>${escapeXML(data.coRelationship === 'Domestic Partner' ? 'Domestic Partner' : 'Spouse')}</Relation>\n`;
            xml += '    </PersonalInfo>\n';
            xml += '    <Address>\n';
            xml += '      <AddressCode>StreetAddress</AddressCode>\n';
            xml += '      <Addr1>\n';
            xml += `        <StreetName>${escapeXML(streetName)}</StreetName>\n`;
            xml += `        <StreetNumber>${escapeXML(streetNumber)}</StreetNumber>\n`;
            xml += '      </Addr1>\n';
            xml += `      <City>${escapeXML(data.addrCity)}</City>\n`;
            xml += `      <StateCode>${escapeXML(state)}</StateCode>\n`;
            if (county) xml += `      <County>${escapeXML(county)}</County>\n`;
            xml += `      <Zip5>${escapeXML(zip5)}</Zip5>\n`;
            const coPhone = data.coPhone ? data.coPhone.replace(/\D/g, '') : '';
            if (coPhone) {
                xml += '      <Phone id="1">\n';
                xml += '        <PhoneType>Mobile</PhoneType>\n';
                xml += `        <PhoneNumber>${escapeXML(coPhone)}</PhoneNumber>\n`;
                xml += '        <Extension></Extension>\n';
                xml += '      </Phone>\n';
            }
            if (data.coEmail) xml += `      <Email>${escapeXML(data.coEmail)}</Email>\n`;
            xml += '    </Address>\n';
            xml += '  </Applicant>\n';
        }

        // PriorPolicyInfo — only emit child date/text elements when they have values
        const priorExp = normalizeDate(data.priorExp);
        xml += '  <PriorPolicyInfo>\n';
        if (data.priorCarrier) {
            xml += `    <PriorCarrier>${escapeXML(data.priorCarrier)}</PriorCarrier>\n`;
        }
        if (data.priorPolicyTerm) {
            xml += `    <PriorPolicyTerm>${escapeXML(data.priorPolicyTerm)}</PriorPolicyTerm>\n`;
        }
        if (priorExp) {
            xml += `    <Expiration>${priorExp}</Expiration>\n`;
        }
        if (data.priorYears) {
            xml += '    <YearsWithPriorCarrier>\n';
            xml += `      <Years>${escapeXML(data.priorYears)}</Years>\n`;
            xml += '    </YearsWithPriorCarrier>\n';
        }
        xml += '  </PriorPolicyInfo>\n';

        // PolicyInfo — only emit when values present
        const effectiveDate = normalizeDate(data.effectiveDate);
        xml += '  <PolicyInfo>\n';
        if (data.policyTerm) {
            xml += `    <PolicyTerm>${escapeXML(data.policyTerm)}</PolicyTerm>\n`;
        }
        if (effectiveDate) {
            xml += `    <Effective>${effectiveDate}</Effective>\n`;
        }
        xml += '  </PolicyInfo>\n';

        // ResidenceInfo section (garage location = mailing address by default)
        xml += '  <ResidenceInfo>\n';
        xml += '    <GarageLocation>\n';
        xml += '      <Address>\n';
        xml += '        <AddressCode>StreetAddress</AddressCode>\n';
        xml += '        <Addr1>\n';
        xml += `          <StreetName>${escapeXML(streetName)}</StreetName>\n`;
        xml += `          <StreetNumber>${escapeXML(streetNumber)}</StreetNumber>\n`;
        xml += '        </Addr1>\n';
        xml += `        <City>${escapeXML(data.addrCity)}</City>\n`;
        xml += `        <StateCode>${escapeXML(state)}</StateCode>\n`;
        if (county) {
            xml += `        <County>${escapeXML(county)}</County>\n`;
        }
        xml += `        <Zip5>${escapeXML(zip5)}</Zip5>\n`;
        xml += '      </Address>\n';
        xml += '    </GarageLocation>\n';
        xml += '  </ResidenceInfo>\n';

        // Drivers section - iterate over drivers array or use flat fields
        xml += '  <Drivers>\n';
        if (drivers) {
            // Use drivers array
            drivers.forEach((driver, index) => {
                const driverDob = normalizeDate(driver.dob);
                const driverId = index + 1;
                const isFirstDriver = index === 0;
                const driverGender = mapGender(driver.gender || data.gender);
                const driverMarital = mapMaritalStatus(driver.maritalStatus || data.maritalStatus);

                xml += `    <Driver id="${driverId}">\n`;
                const driverFirst = driver.firstName || (isFirstDriver ? (data.firstName || '') : '');
                const driverLast = driver.lastName || (isFirstDriver ? (data.lastName || '') : '');
                xml += '      <Name>\n';
                xml += `        <FirstName>${escapeXML(driverFirst)}</FirstName>\n`;
                xml += `        <LastName>${escapeXML(driverLast)}</LastName>\n`;
                xml += '      </Name>\n';
                if (driverGender) {
                    xml += `      <Gender>${escapeXML(driverGender)}</Gender>\n`;
                }
                if (driverDob) {
                    xml += `      <DOB>${driverDob}</DOB>\n`;
                }
                if (driver.dlNum) {
                    xml += `      <DLNumber>${escapeXML((driver.dlNum || '').toUpperCase())}</DLNumber>\n`;
                }
                xml += `      <DLState>${escapeXML((driver.dlState || state).toUpperCase())}</DLState>\n`;
                if (driverMarital) {
                    xml += `      <MaritalStatus>${escapeXML(driverMarital)}</MaritalStatus>\n`;
                }
                if (isFirstDriver) {
                    xml += '      <Relation>Insured</Relation>\n';
                }
                xml += '      <GoodStudent>No</GoodStudent>\n';
                xml += '      <MATDriver>No</MATDriver>\n';
                xml += '      <Rated>Rated</Rated>\n';
                xml += '    </Driver>\n';
            });
        } else {
            // Fallback to flat fields for backward compatibility
            xml += '    <Driver id="1">\n';
            xml += '      <Name>\n';
            xml += `        <FirstName>${escapeXML(data.firstName)}</FirstName>\n`;
            xml += `        <LastName>${escapeXML(data.lastName)}</LastName>\n`;
            xml += '      </Name>\n';
            if (gender) {
                xml += `      <Gender>${escapeXML(gender)}</Gender>\n`;
            }
            xml += `      <DOB>${dob}</DOB>\n`;
            if (data.dlNum) {
                xml += `      <DLNumber>${escapeXML((data.dlNum || '').toUpperCase())}</DLNumber>\n`;
            }
            xml += `      <DLState>${escapeXML((data.dlState || state).toUpperCase())}</DLState>\n`;
            if (marital) {
                xml += `      <MaritalStatus>${escapeXML(marital)}</MaritalStatus>\n`;
            }
            xml += '      <Relation>Insured</Relation>\n';
            xml += '      <GoodStudent>No</GoodStudent>\n';
            xml += '      <MATDriver>No</MATDriver>\n';
            xml += '      <Rated>Rated</Rated>\n';
            xml += '    </Driver>\n';
        }
        xml += '  </Drivers>\n';

        // Vehicles section — only emit if there are vehicles
        const hasVehicles = vehicles ? vehicles.length > 0 : !!(data.vin || data.vehDesc);
        if (hasVehicles) {
            xml += '  <Vehicles>\n';
            if (vehicles) {
                vehicles.forEach((vehicle, index) => {
                    const vehicleId = index + 1;
                    const hasVin = vehicle.vin && vehicle.vin.trim().length > 0;
                    xml += `    <Vehicle id="${vehicleId}">\n`;
                    xml += `      <UseVinLookup>${hasVin ? 'Yes' : 'No'}</UseVinLookup>\n`;
                    xml += `      <Year>${escapeXML(vehicle.year || '')}</Year>\n`;
                    xml += `      <Vin>${escapeXML(vehicle.vin || '')}</Vin>\n`;
                    xml += `      <Make>${escapeXML(vehicle.make || '')}</Make>\n`;
                    xml += `      <Model>${escapeXML(vehicle.model || '')}</Model>\n`;
                    xml += '      <Anti-Theft>None</Anti-Theft>\n';
                    xml += '      <PassiveRestraints>None</PassiveRestraints>\n';
                    xml += '    </Vehicle>\n';
                });
            } else if (data.vin || data.vehDesc) {
                const parseVehicle = (desc) => {
                    const match = desc?.match(/(\d{4})\s+([A-Z]+)\s+(.+)/i);
                    return {
                        year: match?.[1] || '',
                        make: match?.[2] || '',
                        model: match?.[3]?.trim() || ''
                    };
                };
                const { year, make, model } = parseVehicle(data.vehDesc);
                const hasVin = data.vin && data.vin.trim().length > 0;
                xml += '    <Vehicle id="1">\n';
                xml += `      <UseVinLookup>${hasVin ? 'Yes' : 'No'}</UseVinLookup>\n`;
                xml += `      <Year>${escapeXML(year)}</Year>\n`;
                xml += `      <Vin>${escapeXML(data.vin || '')}</Vin>\n`;
                xml += `      <Make>${escapeXML(make)}</Make>\n`;
                xml += `      <Model>${escapeXML(model)}</Model>\n`;
                xml += '      <Anti-Theft>None</Anti-Theft>\n';
                xml += '      <PassiveRestraints>None</PassiveRestraints>\n';
                xml += '    </Vehicle>\n';
            }
            xml += '  </Vehicles>\n';

            // VehiclesUse section
            xml += '  <VehiclesUse>\n';
            if (vehicles) {
                vehicles.forEach((vehicle, index) => {
                    const vehicleId = index + 1;
                    const miles = vehicle.miles || '12000';
                    xml += `    <VehicleUse id="${vehicleId}">\n`;
                    xml += `      <AnnualMiles>${escapeXML(miles)}</AnnualMiles>\n`;
                    xml += '    </VehicleUse>\n';
                });
            } else if (data.vin || data.vehDesc) {
                xml += '    <VehicleUse id="1">\n';
                xml += `      <AnnualMiles>${escapeXML(data.miles || '12000')}</AnnualMiles>\n`;
                xml += '    </VehicleUse>\n';
            }
            xml += '  </VehiclesUse>\n';

            // Coverages section
            const vehCount = vehicles ? vehicles.length : 1;
            const liab = parseLimits(data.liabilityLimits);
            const um = parseLimits(data.umLimits);
            const uim = parseLimits(data.uimLimits);
            const pdValue = data.pdLimit || liab.pd || '100000';
            xml += '  <Coverages>\n';
            xml += '    <GeneralCoverage>\n';
            xml += `      <BI>${escapeXML(liab.bi || data.liabilityLimits || '100/300')}</BI>\n`;
            xml += `      <PD>${escapeXML(pdValue)}</PD>\n`;
            xml += `      <UM>${escapeXML(um.bi || data.umLimits || '100/300')}</UM>\n`;
            xml += `      <UIM>${escapeXML(uim.bi || data.uimLimits || '100/300')}</UIM>\n`;
            xml += `      <Multicar>${vehCount > 1 ? 'Yes' : 'No'}</Multicar>\n`;
            xml += '    </GeneralCoverage>\n';

            // VehicleCoverage per vehicle
            for (let i = 1; i <= vehCount; i++) {
                xml += `    <VehicleCoverage id="${i}">\n`;
                xml += `      <OtherCollisionDeductible>${escapeXML(data.compDeductible || 'No Coverage')}</OtherCollisionDeductible>\n`;
                xml += `      <CollisionDeductible>${escapeXML(data.autoDeductible || 'No Coverage')}</CollisionDeductible>\n`;
                xml += `      <TowingDeductible>${escapeXML(data.towingDeductible || 'No Coverage')}</TowingDeductible>\n`;
                xml += `      <RentalDeductible>${escapeXML(data.rentalDeductible || 'No Coverage')}</RentalDeductible>\n`;
                xml += '    </VehicleCoverage>\n';
            }

            // StateSpecificCoverage
            if (state === 'WA') {
                xml += '    <StateSpecificCoverage>\n';
                xml += '      <WA-Coverages>\n';
                xml += `        <WA-UMPD>${escapeXML(data.umPd || data.pdLimit || liab.pd || '25000')}</WA-UMPD>\n`;
                xml += '        <WA-PIP>10000</WA-PIP>\n';
                xml += '      </WA-Coverages>\n';
                xml += '    </StateSpecificCoverage>\n';
            }

            xml += '  </Coverages>\n';

            // VehicleAssignments section
            xml += '  <VehicleAssignments>\n';
            const driverCount = drivers ? drivers.length : 1;
            for (let i = 1; i <= vehCount; i++) {
                xml += `    <VehicleAssignment id="${i}">\n`;
                let assignedDriver = ((i - 1) % driverCount) + 1;
                if (vehicles && vehicles[i-1]?.primaryDriver && drivers) {
                    const driverIdx = drivers.findIndex(d => d.id === vehicles[i-1].primaryDriver);
                    if (driverIdx >= 0) assignedDriver = driverIdx + 1;
                }
                xml += `      <DriverAssignment>${assignedDriver}</DriverAssignment>\n`;
                xml += '    </VehicleAssignment>\n';
            }
            xml += '  </VehicleAssignments>\n';
        }

        xml += '</EZAUTO>\n';

        return {
            ok: true,
            content: xml,
            filename: `${lastName || 'Lead'}_EZLynx.xml`,
            mime: 'application/xml;charset=utf-8'
        };
    },

    exportHomeXML() {
        const result = this.buildHomeXML(this.data);
        if (!result.ok) {
            this.toast(result.error);
            return;
        }
        this.downloadFile(result.content, result.filename, result.mime);
        this.logExport('HomeXML', result.filename);
        this.toast('🏠 EZLynx Home XML File Generated!');
    },

    buildHomeXML(data) {
        // ─── Shared helpers (from App._xxx methods) ───
        const escapeXML = this._escapeXML;
        const mapMaritalStatus = this._mapMaritalStatus;
        const mapGender = this._mapGender;
        const normalizeDate = this._normalizeDate;
        const splitZip = this._splitZip;
        const cleanNum = (v) => (v || '').toString().replace(/[$,\s]/g, '').trim();

        // ─── Mapping helpers (EZLynx exact values from reference sample) ───
        const mapConstruction = (style) => {
            if (!style) return '';
            const map = { 'Frame': 'Frame', 'Vinyl Siding': 'Siding, Vinyl', 'Masonry Veneer': 'Masonry Veneer', 'Masonry': 'Masonry', 'Stucco': 'Stucco', 'Log': 'Log', 'Adobe': 'Adobe', 'Brick': 'Brick' };
            return map[style] || style;
        };
        const mapDwelling = (dt) => {
            if (!dt) return 'One Family';
            const map = { 'Single Family': 'One Family', 'Condo': 'Condo', 'Townhome': 'Townhouse', 'Duplex': 'Two Family', 'Triplex': 'Three Family', 'Fourplex': 'Four Family' };
            return map[dt] || dt;
        };
        const mapStructure = (dt) => {
            if (!dt) return '';
            const map = { 'Single Family': 'Ranch', 'Condo': 'Condo', 'Townhome': 'Townhouse', 'Colonial': 'Colonial', 'Ranch': 'Ranch', 'Split Level': 'Split Level', 'Cape Cod': 'Cape Cod', 'Victorian': 'Victorian' };
            return map[dt] || dt;
        };
        const mapRoof = (rt) => {
            if (!rt) return '';
            const map = { 'Asphalt/Composite Shingle': 'COMPOSITION', 'Architectural Shingle': 'ARCHITECTURAL SHINGLE', 'Metal': 'METAL', 'Clay Tile': 'CLAY TILE', 'Concrete Tile': 'CONCRETE TILE', 'Wood Shake': 'WOOD SHAKE', 'Slate': 'SLATE', 'Tar & Gravel': 'TAR AND GRAVEL' };
            return map[rt] || rt.toUpperCase();
        };
        const mapFoundation = (f) => {
            if (!f) return '';
            const map = { 'Slab': 'Slab', 'Crawlspace': 'Crawlspace', 'Basement (Finished)': 'Basement - Finished', 'Basement (Unfinished)': 'Basement - Unfinished', 'Pier/Pile': 'Pier' };
            return map[f] || f;
        };
        const mapHeating = (h) => {
            if (!h) return '';
            const map = { 'Forced Air - Gas': 'Gas', 'Forced Air - Electric': 'Electric', 'Heat Pump': 'Heat Pump', 'Boiler (Steam/Water)': 'Hot Water/Steam', 'Electric Baseboard': 'Electric', 'Oil/Kerosene': 'Oil' };
            return map[h] || h;
        };
        const mapDwellingUse = (u) => {
            if (!u) return 'Primary';
            const map = { 'Primary': 'Primary', 'Secondary': 'Secondary', 'Seasonal': 'Seasonal', 'Rental': 'Tenant Occupied', 'Vacant': 'Vacant' };
            return map[u] || u;
        };
        const mapOccupancy = (o) => {
            if (!o) return 'Owner Occupied';
            const map = { 'Owner': 'Owner Occupied', 'Tenant': 'Tenant', 'Vacant': 'Vacant' };
            return map[o] || o;
        };
        // Map form industry values to valid EZLynx/ACORD Industry names.
        // Employment statuses (Retired, Disabled, etc.) are NOT industries
        // and crash .NET enum deserialization — omit them.
        const mapIndustry = (val) => {
            if (!val) return '';
            const notIndustry = ['Retired','Disabled','Unemployed','Student','Homemaker/House person'];
            if (notIndustry.includes(val)) return '';
            const map = {
                'Agriculture/Forestry/Fishing': 'Agriculture/Forestry/Fishing',
                'Art/Design/Media': 'Art/Design/Media',
                'Banking/Finance/Real Estate': 'Banking/Finance/Real Estate',
                'Business/Sales/Office': 'Business/Sales/Office',
                'Construction/Energy Trades': 'Construction/Energy Trades',
                'Education/Library': 'Education/Library',
                'Engineer/Architect/Science/Math': 'Engineer/Architect/Science/Math',
                'Government/Military': 'Government/Military',
                'Information Technology': 'Information Technology',
                'Insurance': 'Insurance',
                'Legal/Law Enforcement/Security': 'Legal/Law Enforcement/Security',
                'Maintenance/Repair/Housekeeping': 'Maintenance/Repair/Housekeeping',
                'Manufacturing/Production': 'Manufacturing/Production',
                'Medical/Social Services/Religion': 'Medical/Social Services/Religion',
                'Personal Care/Service': 'Personal Care/Service',
                'Restaurant/Hotel Services': 'Restaurant/Hotel Services',
                'Sports/Recreation': 'Sports/Recreation',
                'Travel/Transportation/Warehousing': 'Travel/Transportation/Warehousing',
                'Other': 'Other'
            };
            return map[val] || '';
        };
        // Determine update status from year
        const updateStatus = (yr, builtYr) => {
            if (!yr) return 'NOT UPDATED';
            const y = parseInt(yr, 10);
            const b = parseInt(builtYr, 10) || 0;
            if (y >= b + 5) return 'PARTIAL UPDATE';
            return 'NOT UPDATED';
        };

        // ─── Primary applicant resolution ───
        const drivers = (data.drivers && data.drivers.length > 0) ? data.drivers : null;
        const primaryDriver = drivers ? drivers[0] : data;
        const firstName = primaryDriver.firstName || data.firstName || '';
        const lastName = primaryDriver.lastName || data.lastName || '';
        const dob = normalizeDate(primaryDriver.dob || data.dob);

        // ─── Validation ───
        if (!firstName || !lastName) {
            return { ok: false, error: '⚠️ First and last name are required for EZLynx Home XML.' };
        }
        const state = (data.addrState || '').trim().toUpperCase();
        if (!state || !/^[A-Z]{2}$/.test(state)) {
            return { ok: false, error: '⚠️ A valid 2-letter state is required for EZLynx Home XML.' };
        }
        if (!dob) {
            return { ok: false, error: '⚠️ A valid DOB is required for EZLynx Home XML.' };
        }

        // ─── Shared address/contact fields ───
        const phone = data.phone ? data.phone.replace(/\D/g, '') : '';
        const streetRaw = (data.addrStreet || '').trim();
        const streetMatch = streetRaw.match(/^(\d+)\s+(.*)$/);
        const streetNumber = streetMatch?.[1] || '';
        const streetName = streetMatch?.[2] || streetRaw;
        const { zip5, zip4 } = splitZip(data.addrZip);
        const gender = mapGender(primaryDriver.gender || data.gender);
        const marital = mapMaritalStatus(primaryDriver.maritalStatus || data.maritalStatus);
        const county = this.getCountyFromCity(data.addrCity, state);

        // ════════════════════════════════════════
        // START XML — Pretty-printed EZHOME V200 format
        // Structural twin of John_Smith_Home.xml reference
        // ════════════════════════════════════════
        const I = '  ';   // 2-space indent (matches reference file)
        const I2 = I+I, I3 = I2+I, I4 = I3+I;
        const L = '\n';   // newline between elements

        let xml = '<?xml version="1.0" encoding="utf-8"?>' + L;
        xml += '<EZHOME xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.ezlynx.com/XMLSchema/Home/V200">' + L;

        // ── Applicant ──
        xml += I + '<Applicant>' + L;
        xml += I2 + '<ApplicantType>Applicant</ApplicantType>' + L;
        xml += I2 + '<PersonalInfo>' + L;
        xml += I3 + '<Name>' + L;
        xml += I4 + `<FirstName>${escapeXML(firstName)}</FirstName>` + L;
        xml += I4 + '<MiddleName />' + L;
        xml += I4 + `<LastName>${escapeXML(lastName)}</LastName>` + L;
        xml += I3 + '</Name>' + L;
        xml += I3 + `<DOB>${dob}</DOB>` + L;
        if (gender) xml += I3 + `<Gender>${escapeXML(gender)}</Gender>` + L;
        if (marital) xml += I3 + `<MaritalStatus>${escapeXML(marital)}</MaritalStatus>` + L;
        xml += I3 + '<Relation>Insured</Relation>' + L;
        const industry = mapIndustry(data.industry);
        if (industry) xml += I3 + `<Industry>${escapeXML(industry)}</Industry>` + L;
        if (data.occupation) xml += I3 + `<Occupation>${escapeXML(data.occupation)}</Occupation>` + L;
        xml += I2 + '</PersonalInfo>' + L;
        xml += I2 + '<Address>' + L;
        xml += I3 + '<AddressCode>StreetAddress</AddressCode>' + L;
        xml += I3 + '<Addr1>' + L;
        xml += I4 + `<StreetName>${escapeXML(streetName)}</StreetName>` + L;
        xml += I4 + `<StreetNumber>${escapeXML(streetNumber)}</StreetNumber>` + L;
        xml += I4 + '<UnitNumber />' + L;
        xml += I3 + '</Addr1>' + L;
        xml += I3 + '<Addr2 />' + L;
        xml += I3 + `<City>${escapeXML(data.addrCity || '')}</City>` + L;
        xml += I3 + `<StateCode>${escapeXML(state)}</StateCode>` + L;
        if (county) xml += I3 + `<County>${escapeXML(county)}</County>` + L;
        xml += I3 + `<Zip5>${escapeXML(zip5)}</Zip5>` + L;
        if (phone) {
            xml += I3 + '<Phone>' + L;
            xml += I4 + '<PhoneType>Mobile</PhoneType>' + L;
            xml += I4 + `<PhoneNumber>${escapeXML(phone)}</PhoneNumber>` + L;
            xml += I3 + '</Phone>' + L;
        }
        if (data.email) xml += I3 + `<Email>${escapeXML(data.email)}</Email>` + L;
        xml += I3 + '<BridgeEmailToCarriers>No</BridgeEmailToCarriers>' + L;
        xml += I3 + '<PreferredContactMethod>Phone (Mobile)</PreferredContactMethod>' + L;
        if (data.yearsAtAddress) xml += I3 + `<YearsAtAddress>${escapeXML(data.yearsAtAddress)}</YearsAtAddress>` + L;
        xml += I3 + '<Validation>Valid</Validation>' + L;
        xml += I2 + '</Address>' + L;
        xml += I + '</Applicant>' + L;

        // ── Co-Applicant (if provided) ──
        if (data.hasCoApplicant === 'yes' && (data.coFirstName || data.coLastName)) {
            const coDob = normalizeDate(data.coDob);
            const coGender = mapGender(data.coGender);
            xml += I + '<Applicant>' + L;
            xml += I2 + '<ApplicantType>CoApplicant</ApplicantType>' + L;
            xml += I2 + '<PersonalInfo>' + L;
            xml += I3 + '<Name>' + L;
            xml += I4 + `<FirstName>${escapeXML(data.coFirstName || '')}</FirstName>` + L;
            xml += I4 + '<MiddleName />' + L;
            xml += I4 + `<LastName>${escapeXML(data.coLastName || '')}</LastName>` + L;
            xml += I3 + '</Name>' + L;
            if (coDob) xml += I3 + `<DOB>${coDob}</DOB>` + L;
            if (coGender) xml += I3 + `<Gender>${escapeXML(coGender)}</Gender>` + L;
            if (marital) xml += I3 + `<MaritalStatus>${escapeXML(marital)}</MaritalStatus>` + L;
            xml += I3 + `<Relation>${escapeXML(data.coRelationship === 'Domestic Partner' ? 'Domestic Partner' : 'Spouse')}</Relation>` + L;
            xml += I2 + '</PersonalInfo>' + L;
            xml += I2 + '<Address>' + L;
            xml += I3 + '<AddressCode>StreetAddress</AddressCode>' + L;
            xml += I3 + '<Addr1>' + L;
            xml += I4 + `<StreetName>${escapeXML(streetName)}</StreetName>` + L;
            xml += I4 + `<StreetNumber>${escapeXML(streetNumber)}</StreetNumber>` + L;
            xml += I4 + '<UnitNumber />' + L;
            xml += I3 + '</Addr1>' + L;
            xml += I3 + '<Addr2 />' + L;
            xml += I3 + `<City>${escapeXML(data.addrCity || '')}</City>` + L;
            xml += I3 + `<StateCode>${escapeXML(state)}</StateCode>` + L;
            if (county) xml += I3 + `<County>${escapeXML(county)}</County>` + L;
            xml += I3 + `<Zip5>${escapeXML(zip5)}</Zip5>` + L;
            const coPhone = data.coPhone ? data.coPhone.replace(/\D/g, '') : '';
            if (coPhone) {
                xml += I3 + '<Phone>' + L;
                xml += I4 + '<PhoneType>Mobile</PhoneType>' + L;
                xml += I4 + `<PhoneNumber>${escapeXML(coPhone)}</PhoneNumber>` + L;
                xml += I3 + '</Phone>' + L;
            }
            if (data.coEmail) xml += I3 + `<Email>${escapeXML(data.coEmail)}</Email>` + L;
            xml += I3 + '<Validation>Valid</Validation>' + L;
            xml += I2 + '</Address>' + L;
            xml += I + '</Applicant>' + L;
        }

        // ── PriorPolicyInfo (home-specific fields) ──
        const homePriorCarrier = data.homePriorCarrier || data.priorCarrier || '';
        const homePriorYears = data.homePriorYears || data.priorYears || '';
        const homePriorExpDate = normalizeDate(data.homePriorExp || data.priorExp);
        xml += I + '<PriorPolicyInfo>' + L;
        if (homePriorCarrier) xml += I2 + `<PriorCarrier>${escapeXML(homePriorCarrier)}</PriorCarrier>` + L;
        if (homePriorExpDate) xml += I2 + `<Expiration>${homePriorExpDate}</Expiration>` + L;
        if (homePriorYears) {
            const yearsInt = parseInt(String(homePriorYears).replace(/[^0-9]/g, ''), 10) || 0;
            xml += I2 + '<YearsWithPriorCarrier>' + L;
            xml += I3 + `<Years>${yearsInt}</Years>` + L;
            xml += I3 + '<Months>0</Months>' + L;
            xml += I2 + '</YearsWithPriorCarrier>' + L;
            xml += I2 + '<YearsWithContinuousCoverage>' + L;
            xml += I3 + `<Years>${yearsInt}</Years>` + L;
            xml += I3 + '<Months>0</Months>' + L;
            xml += I2 + '</YearsWithContinuousCoverage>' + L;
        }
        xml += I + '</PriorPolicyInfo>' + L;

        // ── PolicyInfo ──
        const effectiveDate = normalizeDate(data.effectiveDate) || new Date().toISOString().split('T')[0];
        const policyType = data.homePolicyType || 'HO3';
        xml += I + '<PolicyInfo>' + L;
        xml += I2 + `<PolicyTerm>${escapeXML(data.policyTerm || '12 Month')}</PolicyTerm>` + L;
        xml += I2 + `<PolicyType>${escapeXML(policyType)}</PolicyType>` + L;
        xml += I2 + '<Package>No</Package>' + L;
        xml += I2 + `<Effective>${effectiveDate}</Effective>` + L;
        xml += I2 + '<CreditCheckAuth>Yes</CreditCheckAuth>' + L;
        xml += I + '</PolicyInfo>' + L;

        // ── RatingInfo (strict positional sequence from John_Smith reference) ──
        const yrBuilt = data.yrBuilt || '';
        xml += I + '<RatingInfo>' + L;
        xml += I2 + '<PropertyInsCancelledLapsed>No</PropertyInsCancelledLapsed>' + L;
        if (yrBuilt) xml += I2 + `<YearBuilt>${escapeXML(yrBuilt)}</YearBuilt>` + L;
        xml += I2 + `<Dwelling>${escapeXML(mapDwelling(data.dwellingType))}</Dwelling>` + L;
        xml += I2 + `<NumberOfOccupants>${escapeXML(data.numOccupants || '1')}</NumberOfOccupants>` + L;
        xml += I2 + `<DwellingUse>${escapeXML(mapDwellingUse(data.dwellingUsage))}</DwellingUse>` + L;
        xml += I2 + `<DwellingOccupancy>${escapeXML(mapOccupancy(data.occupancyType))}</DwellingOccupancy>` + L;

        // Fire protection — all tags always present for positional deserializer
        if (data.fireHydrantFeet) xml += I2 + `<DistanceToFireHydrant>${escapeXML(data.fireHydrantFeet)}</DistanceToFireHydrant>` + L;
        xml += I2 + '<WithinCityLimits>No</WithinCityLimits>' + L;
        if (data.fireStationDist) {
            // Round to integer — V200 schema expects int for DistanceToFireStation
            const fireDist = Math.round(parseFloat(data.fireStationDist)) || data.fireStationDist;
            xml += I2 + `<DistanceToFireStation>${escapeXML(String(fireDist))}</DistanceToFireStation>` + L;
        }
        // Omit DistanceToFireStation entirely when no data — self-closing
        // <DistanceToFireStation /> crashes .NET int deserialization
        xml += I2 + '<WithinFireDistrict>No</WithinFireDistrict>' + L;
        if (data.protectionClass) xml += I2 + `<ProtectionClass>${escapeXML(data.protectionClass)}</ProtectionClass>` + L;

        // Structure — always present
        xml += I2 + `<NumberOfStories>${escapeXML(data.numStories || '1')}</NumberOfStories>` + L;
        if (data.fullBaths) xml += I2 + `<NumberOfFullBaths>${escapeXML(data.fullBaths)}</NumberOfFullBaths>` + L;
        if (data.halfBaths && data.halfBaths !== '0') xml += I2 + `<NumberOfHalfBaths>${escapeXML(data.halfBaths)}</NumberOfHalfBaths>` + L;

        const construction = mapConstruction(data.constructionStyle || data.exteriorWalls);
        if (construction) xml += I2 + `<Construction>${escapeXML(construction)}</Construction>` + L;
        const structure = mapStructure(data.dwellingType);
        if (structure) xml += I2 + `<Structure>${escapeXML(structure)}</Structure>` + L;
        const roof = mapRoof(data.roofType);
        if (roof) xml += I2 + `<Roof>${escapeXML(roof)}</Roof>` + L;

        // Pool & Dogs — right after Roof
        xml += I2 + `<SwimmingPool>${(data.pool && data.pool !== 'None') ? 'Yes' : 'No'}</SwimmingPool>` + L;
        xml += I2 + `<SwimmingPoolFenced>${(data.pool && data.pool.includes('Ground')) ? 'Yes' : 'No'}</SwimmingPoolFenced>` + L;
        xml += I2 + `<DogOnPremises>${data.dogInfo ? 'Yes' : 'No'}</DogOnPremises>` + L;

        // Heating type
        const heating = mapHeating(data.heatingType);
        if (heating) xml += I2 + `<HeatingType>${escapeXML(heating)}</HeatingType>` + L;

        // System updates — always emit UpdateYear (default to yrBuilt)
        xml += I2 + `<RoofingUpdate>${updateStatus(data.roofYr, yrBuilt)}</RoofingUpdate>` + L;
        xml += I2 + `<RoofingUpdateYear>${escapeXML(data.roofYr || yrBuilt)}</RoofingUpdateYear>` + L;
        xml += I2 + `<ElectricalUpdate>${updateStatus(data.elecYr, yrBuilt)}</ElectricalUpdate>` + L;
        xml += I2 + `<ElectricalUpdateYear>${escapeXML(data.elecYr || yrBuilt)}</ElectricalUpdateYear>` + L;
        xml += I2 + `<PlumbingUpdate>${updateStatus(data.plumbYr, yrBuilt)}</PlumbingUpdate>` + L;
        xml += I2 + `<PlumbingUpdateYear>${escapeXML(data.plumbYr || yrBuilt)}</PlumbingUpdateYear>` + L;
        xml += I2 + `<HeatingUpdate>${updateStatus(data.heatYr, yrBuilt)}</HeatingUpdate>` + L;
        xml += I2 + `<HeatingUpdateYear>${escapeXML(data.heatYr || yrBuilt)}</HeatingUpdateYear>` + L;

        xml += I2 + '<UnderConstruction>No</UnderConstruction>' + L;
        if (data.sqFt) xml += I2 + `<SquareFootage>${escapeXML(data.sqFt)}</SquareFootage>` + L;
        const purchaseDate = normalizeDate(data.purchaseDate);
        if (purchaseDate) xml += I2 + `<PurchaseDate>${purchaseDate}</PurchaseDate>` + L;

        xml += I2 + `<Trampoline>${(data.trampoline && data.trampoline !== 'None') ? 'Yes' : 'No'}</Trampoline>` + L;
        xml += I2 + `<BusinessOnPremises>${data.businessOnProperty ? 'Yes' : 'No'}</BusinessOnPremises>` + L;
        xml += I2 + `<FirstMortgagee>${data.mortgagee ? 'Yes' : 'No'}</FirstMortgagee>` + L;
        xml += I2 + '<SecondMortgagee>No</SecondMortgagee>' + L;
        xml += I2 + '<ThirdMortgagee>No</ThirdMortgagee>' + L;
        xml += I2 + '<EquityLineOfCredit>No</EquityLineOfCredit>' + L;
        xml += I2 + '<CoSigner>No</CoSigner>' + L;
        xml += I2 + '<NumberOfOtherInterests>0</NumberOfOtherInterests>' + L;

        const foundation = mapFoundation(data.foundation);
        if (foundation) xml += I2 + `<Foundation>${escapeXML(foundation)}</Foundation>` + L;
        if (data.roofShape) xml += I2 + `<RoofDesign>${escapeXML(data.roofShape)}</RoofDesign>` + L;
        xml += I + '</RatingInfo>' + L;

        // ── ReplacementCost — always emit dwelling value (default 0) ──
        xml += I + '<ReplacementCost>' + L;
        const dwellingCov = cleanNum(data.dwellingCoverage) || '0';
        xml += I2 + `<ReplacementCost>${escapeXML(dwellingCov)}</ReplacementCost>` + L;
        xml += I2 + `<Dwelling>${escapeXML(dwellingCov)}</Dwelling>` + L;
        xml += I2 + '<LossOfUse>0</LossOfUse>' + L;
        const liability = cleanNum(data.personalLiability) || '0';
        xml += I2 + `<PersonalLiability>${escapeXML(liability)}</PersonalLiability>` + L;
        const medPay = cleanNum(data.medicalPayments) || '0';
        xml += I2 + `<MedicalPayments>${escapeXML(medPay)}</MedicalPayments>` + L;
        const deductible = cleanNum(data.homeDeductible);
        xml += I2 + '<DeductibeInfo>' + L;
        xml += I3 + `<Deductible>${escapeXML(deductible || '1000')}</Deductible>` + L;
        xml += I2 + '</DeductibeInfo>' + L;
        xml += I2 + '<RatingCredits>' + L;
        xml += I3 + '<RetireesCredit>No</RetireesCredit>' + L;
        xml += I3 + '<MatureDiscount>No</MatureDiscount>' + L;
        xml += I3 + '<RetirementCommunity>No</RetirementCommunity>' + L;
        xml += I3 + '<LimitedAccessCommunity>No</LimitedAccessCommunity>' + L;
        xml += I3 + '<GatedCommunity>No</GatedCommunity>' + L;
        xml += I3 + '<Multipolicy>No</Multipolicy>' + L;
        xml += I3 + '<NonSmoker>Yes</NonSmoker>' + L;
        xml += I2 + '</RatingCredits>' + L;
        xml += I + '</ReplacementCost>' + L;

        // ── Endorsements ──
        xml += I + '<Endorsements>' + L;
        xml += I2 + '<SpecialPersonalProperty>No</SpecialPersonalProperty>' + L;
        xml += I2 + '<ProtectiveDevices>' + L;
        xml += I3 + '<BurglarAlarm>' + L;
        const hasDeadbolt = (data.burglarAlarm && data.burglarAlarm !== 'None') ? 'Yes' : 'No';
        xml += I4 + `<DeadBolt>${hasDeadbolt}</DeadBolt>` + L;
        xml += I4 + '<VisibleToNeighbor>No</VisibleToNeighbor>' + L;
        xml += I4 + '<MannedSecurity>No</MannedSecurity>' + L;
        xml += I3 + '</BurglarAlarm>' + L;
        xml += I2 + '</ProtectiveDevices>' + L;
        xml += I2 + '<Sinkhole>' + L;
        xml += I3 + '<SinkholeCollapse>No</SinkholeCollapse>' + L;
        xml += I2 + '</Sinkhole>' + L;
        xml += I + '</Endorsements>' + L;

        // ── GeneralInfo ──
        xml += I + '<GeneralInfo>' + L;
        xml += I2 + `<RatingStateCode>${escapeXML(state)}</RatingStateCode>` + L;
        xml += I + '</GeneralInfo>' + L;

        // ── ExtendedInfo blocks (agency credentials for WA rater) ──
        xml += I + '<ExtendedInfo name="ICQ|CARRIERS|ST_WA">' + L;
        xml += I2 + '<valuepair name="carriers_list">' + L;
        xml += I3 + '<value>1029,835,1157,388,429</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I + '</ExtendedInfo>' + L;

        xml += I + '<ExtendedInfo name="ICQ|CROSSREF|ST_WA">' + L;
        xml += I2 + '<valuepair name="343">' + L;
        xml += I3 + '<value>1029</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="225">' + L;
        xml += I3 + '<value>835</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="377">' + L;
        xml += I3 + '<value>1157</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="35">' + L;
        xml += I3 + '<value>388</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="13">' + L;
        xml += I3 + '<value>429</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I + '</ExtendedInfo>' + L;

        xml += I + '<ExtendedInfo name="ICQ|NAME_VALUE_PAIRS">' + L;
        xml += I2 + '<valuepair name="coverage_paperless_common">' + L;
        xml += I3 + '<value>Yes</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="prior_liabilityasiMI">' + L;
        xml += I3 + '<value>org.asicorp_301K+</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="paidinfullasixmlny">' + L;
        xml += I3 + '<value>org.asicorp_MortgageBilled</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="booktransfer">' + L;
        xml += I3 + '<value />' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="textPurchaseDate">' + L;
        xml += I3 + '<value />' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="textInspectionDate">' + L;
        xml += I3 + '<value />' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="endorsements_equipbreakdown_common">' + L;
        xml += I3 + '<value>No</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="endorsements_serviceline_common">' + L;
        xml += I3 + '<value>No</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="textOrdinanceOrLawPercent">' + L;
        xml += I3 + '<value />' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="bicycleamt">' + L;
        xml += I3 + '<value />' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="homeshieldUT_asi">' + L;
        xml += I3 + '<value>None</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="packagesafecoWA">' + L;
        xml += I3 + '<value>A</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="packagexmlKY">' + L;
        xml += I3 + '<value>org.asicorp_PPDNone</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="coverage_winddeductible__377">' + L;
        xml += I3 + '<value>1000</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="acvxml3__377">' + L;
        xml += I3 + '<value>org.asicorp_RC</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="agentcode__343">' + L;
        xml += I3 + '<value>0057</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="cyber_common__343">' + L;
        xml += I3 + '<value>N</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="graduate__225">' + L;
        xml += I3 + '<value>N</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="agentid__35">' + L;
        xml += I3 + '<value>013575</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="producername__35">' + L;
        xml += I3 + '<value />' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="safeco_personalproperty__35">' + L;
        xml += I3 + '<value>No</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="agencycode__13">' + L;
        xml += I3 + '<value>0cfj97</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="coveragelevel__13">' + L;
        xml += I3 + '<value />' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="solarpanels__13">' + L;
        xml += I3 + '<value />' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="carstall__13">' + L;
        xml += I3 + '<value />' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="autopolicylimit__13">' + L;
        xml += I3 + '<value />' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="accidentsaz__13">' + L;
        xml += I3 + '<value>0</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I + '</ExtendedInfo>' + L;

        xml += I + '<ExtendedInfo name="ICQ|CARRIERSTAB|ST_WA">' + L;
        xml += I2 + '<valuepair name="coverage_winddeductible__377">' + L;
        xml += I3 + '<value>1157</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="acvxml3__377">' + L;
        xml += I3 + '<value>1157</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="agentcode__343">' + L;
        xml += I3 + '<value>1029</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="cyber_common__343">' + L;
        xml += I3 + '<value>1029</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="graduate__225">' + L;
        xml += I3 + '<value>835</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="agentid__35">' + L;
        xml += I3 + '<value>388</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="producername__35">' + L;
        xml += I3 + '<value>388</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="safeco_personalproperty__35">' + L;
        xml += I3 + '<value>388</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="agencycode__13">' + L;
        xml += I3 + '<value>429</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="coveragelevel__13">' + L;
        xml += I3 + '<value>429</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="solarpanels__13">' + L;
        xml += I3 + '<value>429</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="carstall__13">' + L;
        xml += I3 + '<value>429</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="autopolicylimit__13">' + L;
        xml += I3 + '<value>429</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="accidentsaz__13">' + L;
        xml += I3 + '<value>429</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="__completed__">' + L;
        xml += I3 + '<value>true</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="__carriers_list_at_last_run__">' + L;
        xml += I3 + '<value>1029,835,1157,388,429</value>' + L;
        xml += I2 + '</valuepair>' + L;
        xml += I2 + '<valuepair name="__last_run_datetime__">' + L;
        xml += I3 + `<value>${new Date().toISOString().split('.')[0]}</value>` + L;
        xml += I2 + '</valuepair>' + L;
        xml += I + '</ExtendedInfo>' + L;

        xml += '</EZHOME>' + L;

        return {
            ok: true,
            content: xml,
            filename: `${lastName || 'Lead'}_EZLynx_Home.xml`,
            mime: 'application/xml;charset=utf-8'
        };
    },
});
