// Auto-generated from EZLynx scrape data  2026-02-20
// This is the built-in schema that ships with the extension.
// To update: scrape EZLynx pages, then use the Export Schema button in popup.
// eslint-disable-next-line no-unused-vars
const DEFAULT_SCHEMA = {
  "Prefix": [
    "MR",
    "MRS",
    "MS",
    "DR"
  ],
  "Suffix": [
    "JR",
    "SR",
    "I",
    "II",
    "III"
  ],
  "Address State": [
    "AK",
    "AL",
    "AR",
    "AZ",
    "CA",
    "CO",
    "CT",
    "DC",
    "DE",
    "FL",
    "GA",
    "HI",
    "IA",
    "ID",
    "IL",
    "IN",
    "KS",
    "KY",
    "LA",
    "MA",
    "MD",
    "ME",
    "MI",
    "MN",
    "MO",
    "MS",
    "MT",
    "NC",
    "ND",
    "NE",
    "NH",
    "NJ",
    "NM",
    "NV",
    "NY",
    "OH",
    "OK",
    "OR",
    "PA",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VA",
    "VT",
    "WA",
    "WI",
    "WV",
    "WY"
  ],
  "Gender": [
    "Female",
    "Male",
    "Not Specified"
  ],
  "Marital Status": [
    "Single",
    "Married",
    "Domestic Partner",
    "Widowed",
    "Separated",
    "Divorced"
  ],
  "DL Status": [
    "Valid",
    "Permit",
    "Expired",
    "Suspended",
    "Cancelled",
    "Not Licensed",
    "Permanently Revoked"
  ],
  "DL State": [
    "AK",
    "AL",
    "AR",
    "AZ",
    "CA",
    "CO",
    "CT",
    "DC",
    "DE",
    "FL",
    "GA",
    "HI",
    "IA",
    "ID",
    "IL",
    "IN",
    "KS",
    "KY",
    "LA",
    "MA",
    "MD",
    "ME",
    "MI",
    "MN",
    "MO",
    "MS",
    "MT",
    "NC",
    "ND",
    "NE",
    "NH",
    "NJ",
    "NM",
    "NV",
    "NY",
    "OH",
    "OK",
    "OR",
    "PA",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VA",
    "VT",
    "WA",
    "WI",
    "WV",
    "WY",
    "Canada",
    "Mexico",
    "International"
  ],
  "Education": [
    "No High School Diploma",
    "High School Diploma",
    "Some College - No Degree",
    "Vocational/Technical Degree",
    "Associates Degree",
    "Bachelors",
    "Masters",
    "Phd",
    "Medical Degree",
    "Law Degree"
  ],
  "Industry": [
    "Homemaker/House person",
    "Retired",
    "Disabled",
    "Unemployed",
    "Student",
    "Agriculture/Forestry/Fishing",
    "Art/Design/Media",
    "Banking/Finance/Real Estate",
    "Business/Sales/Office",
    "Construction/Energy Trades",
    "Education/Library",
    "Engineer/Architect/Science/Math",
    "Government/Military",
    "Information Technology",
    "Insurance",
    "Legal/Law Enforcement/Security",
    "Maintenance/Repair/Housekeeping",
    "Manufacturing/Production",
    "Medical/Social Services/Religion",
    "Personal Care/Service",
    "Restaurant/Hotel Services",
    "Sports/Recreation",
    "Travel/Transportation/Warehousing",
    "Other"
  ],
  "Applicant Type": [
    "Unknown",
    "Prospect/Lead",
    "Active Client",
    "Inactive Client"
  ],
  "Lead source": [
    "Ad - Mailing Campaign",
    "Ad - Other",
    "Ad - Print",
    "Ad - Television",
    "Agency Mgmt System",
    "Agency Website",
    "AgentInsure",
    "AgentInsure Call Me",
    "Bank Rate",
    "Bing",
    "CAP Web Services",
    "Client Center",
    "Conversion",
    "Email",
    "EverQuote,Inc.",
    "EZLynx Consumer Lead Portal",
    "EZLynx Consumer Quoting",
    "EZLynx Consumer Quoting Live",
    "EZUpload",
    "Facebook Consumer Quoting App",
    "Friends/Family",
    "Google",
    "Insurance Quote Exchange",
    "Lead Generator",
    "Lead Generator - Insuranceagents.com",
    "Lead Generator - InsuranceLeads",
    "Lead Generator - InsureMe",
    "Lead Generator - Insweb",
    "Lead Generator - NetQuote",
    "Lead Generator - QuoteWizard",
    "Lead Generator - ZipSearch",
    "Other",
    "Other Search Engine",
    "Phone",
    "Public Relations",
    "Referral - Agent",
    "Referral - Client",
    "Referral - Client Center",
    "Referral - Employee",
    "Referral - External",
    "Referral - Other",
    "Referral - Partner",
    "Sales Center X-Date",
    "Underground Elephant",
    "Web",
    "Word of Mouth",
    "Yahoo",
    "Zapier"
  ],
  "Preferred Language": [
    "Amharic",
    "Arabic",
    "Armenian",
    "Bengali",
    "Cambodian",
    "Chinese - Cantonese",
    "Chinese - Mandarin",
    "Dari",
    "Dutch",
    "English",
    "Farsi",
    "Filipino",
    "French",
    "French Creole",
    "German",
    "Greek",
    "Gujarati",
    "Haitian Creole",
    "Hebrew",
    "Hindi",
    "Hmong",
    "Ilocano",
    "Italian",
    "Japanese",
    "Khmer",
    "Korean",
    "Laotian",
    "Navajo",
    "Persian",
    "Polish",
    "Portuguese",
    "Punjabi",
    "Romanian",
    "Russian",
    "Samoan",
    "Serbo-Croatian",
    "Spanish",
    "Swahili",
    "Tagalog",
    "Tajik",
    "Tamil",
    "Telugu",
    "Thai",
    "Ukrainian",
    "Urdu",
    "Vietnamese",
    "Yoruba"
  ],
  "Address Type": [
    "Home",
    "Mailing",
    "Office",
    "Billing",
    "Seasonal",
    "Rental",
    "Other",
    "Business"
  ],
  "State": [
    "AK",
    "AL",
    "AR",
    "AZ",
    "CA",
    "CO",
    "CT",
    "DC",
    "DE",
    "FL",
    "GA",
    "HI",
    "IA",
    "ID",
    "IL",
    "IN",
    "KS",
    "KY",
    "LA",
    "MA",
    "MD",
    "ME",
    "MI",
    "MN",
    "MO",
    "MS",
    "MT",
    "NC",
    "ND",
    "NE",
    "NH",
    "NJ",
    "NM",
    "NV",
    "NY",
    "OH",
    "OK",
    "OR",
    "PA",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VA",
    "VT",
    "WA",
    "WI",
    "WV",
    "WY"
  ],
  "Years At Address": [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15"
  ],
  "Months At Address": [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11"
  ],
  "Phone Type": [
    "Home",
    "Work",
    "Fax",
    "Mobile"
  ],
  "Email Type": [
    "Primary",
    "Secondary"
  ],
  "Contact Method": [
    "Mobile Phone",
    "Email"
  ],
  "Occupation": [
    "Accountant/Auditor",
    "Actuarial Clerk",
    "Actuary",
    "Administrative Assistant",
    "Agent/Broker",
    "Analyst",
    "Attorney",
    "Claims Adjuster",
    "Clerk",
    "Commissioner",
    "Customer Service Representative",
    "Director/Administrator",
    "Executive",
    "Other",
    "Product Manager",
    "Receptionist/Secretary",
    "Sales Representative",
    "Underwriter"
  ],
  "County": [
    "Adams",
    "Asotin",
    "Benton",
    "Chelan",
    "Clallam",
    "Clark",
    "Columbia",
    "Cowlitz",
    "Douglas",
    "Ferry",
    "Franklin",
    "Garfield",
    "Grant",
    "Grays Harbor",
    "Island",
    "Jefferson",
    "King",
    "Kitsap",
    "Kittitas",
    "Klickitat",
    "Lewis",
    "Lincoln",
    "Mason",
    "Okanogan",
    "Pacific",
    "Pend Oreille",
    "Pierce",
    "San Juan",
    "Skagit",
    "Skamania",
    "Snohomish",
    "Spokane",
    "Stevens",
    "Thurston",
    "Wahkiakum",
    "Walla Walla",
    "Whatcom",
    "Whitman",
    "Yakima"
  ],
  "Prior Carrier": [
    "Other Standard",
    "Other Non-Standard",
    "No Prior Insurance",
    "1st Auto",
    "21st Century",
    "A.Central",
    "AAA",
    "AARP",
    "Acadia",
    "Acceptance Insurance",
    "Access General",
    "Ace",
    "Acuity",
    "Adirondack Ins Exchange",
    "Aegis",
    "Affirmative",
    "Ag Workers Mutual Auto",
    "AIC",
    "AIG",
    "Alert Auto Insurance Company",
    "Alfa Alliance",
    "Alinsco",
    "Allied Trust Insurance Company",
    "Allied",
    "Allstate",
    "America First",
    "American Commerce",
    "American Family",
    "American Freedom Insurance Company",
    "American National",
    "Amerisure",
    "Amica",
    "AmShield",
    "AmWINS Star",
    "Anchor General",
    "Arrowhead Everest",
    "Arrowhead",
    "ASI Lloyds",
    "ASI Select Auto Insurance Corp",
    "Aspen",
    "Aspire",
    "AssuranceAmerica",
    "Atlantic Mutual",
    "Austin Mutual",
    "Autoone",
    "Auto-Owners",
    "AutoTex",
    "Badger Mutual",
    "Balboa",
    "Bankers",
    "Beacon National",
    "Bear River Mutual",
    "Brethern Mutual",
    "Bristol West",
    "Buckeye",
    "California Casualty",
    "Cameron Mutual",
    "Capital Insurance Group",
    "Capitol Insurance Company",
    "Casualty Underwriters Insurance Company",
    "Celina",
    "Centennial",
    "Central Mutual of OH",
    "Century National",
    "Charter",
    "Chubb",
    "Cincinnati Casualty",
    "Cincinnati Insurance",
    "Citizens",
    "Clearcover",
    "CNA",
    "Colonial Penn",
    "Colorado Casualty",
    "Columbia",
    "Commerce West",
    "Commonwealth",
    "Concord Group Insurance",
    "Connect Banner",
    "Constitutional Casualty",
    "Consumers",
    "Cornerstone",
    "Country Insurance",
    "Countryway Insurance",
    "Countrywide",
    "Cover Insurance",
    "CSE",
    "Cumberland",
    "Dairyland",
    "Deerbrook",
    "Delta Lloyds Insurance Company",
    "Depositors",
    "Direct General",
    "Direct",
    "Discovery",
    "Donegal",
    "Drive",
    "Electric",
    "Elephant Insurance",
    "Embark General",
    "EMC",
    "Empower",
    "Encompass",
    "Encova Exceed",
    "Enumclaw Insurance",
    "Erie",
    "Esurance",
    "Eveready",
    "Explorer",
    "Farm Bureau",
    "Farmers",
    "Federated",
    "Fidelity",
    "Financial Indemnity",
    "Firemans Fund",
    "First Acceptance",
    "First American",
    "First Auto",
    "First Chicago",
    "First Connect",
    "Fitchburg Mutual",
    "Flagship Insurance",
    "Foremost",
    "Founders",
    "Frankenmuth",
    "Fred Loya",
    "Fremont Insurance",
    "GAINSCO Auto Insurance",
    "Gateway",
    "Geico",
    "General Casualty",
    "Germania Insurance",
    "Germantown Mutual",
    "GMAC",
    "Goodville Mutual",
    "Grange Insurance Association",
    "Grange",
    "GRE/Go America",
    "Great American",
    "Grinnell",
    "Guide One",
    "Hallmark Insurance Company",
    "Hanover",
    "Harbor",
    "Harleysville",
    "Hartford OMNI",
    "Hartford",
    "Hastings Mutual",
    "Haulers Insurance Company",
    "Hawkeye Security",
    "HDI",
    "Hochheim Prairie Insurance",
    "Horace Mann",
    "Houston General",
    "IFA",
    "Imperial Casualty",
    "IMT Ins",
    "Indiana Farmers",
    "Indiana",
    "Infinity",
    "Insuremax",
    "Insurequest",
    "Integon",
    "Integrity",
    "Iowa Mutual Insurance Company",
    "Kemper Specialty",
    "Kemper",
    "Kingsway",
    "Legacy - Arizona Auto Ins. Co",
    "LeMars Insurance",
    "Liberty Mutual",
    "Liberty Northwest",
    "Madison Mutual Insurance Company",
    "Maidstone Insurance",
    "MAIF",
    "Main Street America",
    "Mapfre",
    "Markel",
    "Maryland Auto Insurance",
    "Mendakota",
    "Mendota",
    "Merchants Group",
    "Mercury",
    "MetLife",
    "Metropolitan",
    "Michigan Insurance Company",
    "Michigan Millers Mutual Insurance Company",
    "Mid-Continent",
    "Midwestern Indemnity",
    "Mile Auto",
    "MMG Insurance Company",
    "Montgomery",
    "Motor Club Insurance Company",
    "Motorists Mutual",
    "MSA",
    "Mt. Washington",
    "Mutual Benefit",
    "Mutual of Enumclaw",
    "National General",
    "National Lloyds Insurance Company",
    "Nationwide",
    "New York Central Mutual",
    "NJ Manufacturers",
    "NJ Skylands",
    "NLC Insurance Companies",
    "Nodak Mutual",
    "Northern Neck Insurance Company",
    "Northstar",
    "NYAIP",
    "NYCM Standard",
    "Occidental",
    "Ocean Harbor",
    "Ohio Casualty",
    "Ohio Mutual",
    "Omaha P/C",
    "Omni Insurance Co",
    "One Beacon",
    "Oregon Mutual",
    "Palisades",
    "Partners Mutual Insurance",
    "Patriot",
    "Patrons Oxford",
    "Peerless/Montgomery",
    "Pekin",
    "Pemco",
    "Peninsula Insurance Companies",
    "Penn National",
    "Personal Service Insurance",
    "Phoenix Indemnity",
    "Pioneer State Mutual",
    "Plymouth Rock",
    "Preferred Mutual",
    "Proformance",
    "Progressive",
    "Providence Mutual Fire Insurance Company",
    "Prudential",
    "QBE",
    "Quincy Mutual",
    "RAM Mutual Insurance Company",
    "Republic",
    "Response",
    "Rockford Mutual",
    "Rockingham Casualty Company",
    "Royal and Sun Alliance",
    "Safe Auto",
    "Safeco",
    "Safety Insurance Company",
    "Safeway",
    "Sagamore",
    "SECURA",
    "Selective",
    "Sentry Ins",
    "Sheboygan Falls Insurance",
    "Shelter Insurance",
    "Southern County",
    "Southern Mutual",
    "Southern Trust",
    "St. Paul/Travelers",
    "Standard Mutual",
    "Star Casualty",
    "State Auto",
    "State Farm",
    "StillWater",
    "Stonegate",
    "Sublimity Insurance Company",
    "Sun Coast Platinum",
    "Texas Ranger MGA",
    "The General",
    "Titan",
    "Topa",
    "Tower",
    "Travelers",
    "TWFG",
    "Unigard",
    "United Automobile",
    "United Fire and Casualty",
    "United Heritage Property and Casualty Company",
    "United Home",
    "Unitrin",
    "Universal",
    "USAA",
    "Utica National",
    "Victoria",
    "Wadena Insurance Company",
    "Wayne Mutual Insurance Company",
    "West Bend",
    "Western National",
    "Western Reserve Group",
    "Westfield",
    "White Mountains",
    "Wilshire",
    "Wilson Mutual",
    "Wind Haven",
    "Windsor",
    "Wisconsin Mutual",
    "Wolverine Mutual Insurance Company",
    "Workmens Auto Insurance Company",
    "Worth Casualty Insurance Company",
    "Zurich"
  ],
  "Prior Liability Limits": [
    "State Minimum",
    "25/50",
    "50/50",
    "50/100",
    "100/100",
    "100/300",
    "250/500",
    "300/300",
    "500/500",
    "1000/1000",
    "55CSL",
    "100CSL",
    "300CSL",
    "500CSL"
  ],
  "Prior Policy Term": [
    "6 Month",
    "12 Month"
  ],
  "Years with Prior Carrier": [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "More than 15"
  ],
  "Months": [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11"
  ],
  "Years with Continuous Coverage": [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "More than 15"
  ],
  "Credit Check and Other Underwriting Reports Authorized": [
    "Yes",
    "No"
  ],
  "New Policy Term": [
    "6 Month",
    "12 Month"
  ],
  "Package": [
    "Yes",
    "No"
  ],
  "Yes": [
    "Yes",
    "No"
  ],
  "Base": [
    "Base",
    "Named Operator Policy"
  ],
  "Gender (2)": [
    "Male",
    "Female",
    "Not Specified"
  ],
  "Occupation Industry": [
    "Homemaker/House person",
    "Retired",
    "Disabled",
    "Unemployed",
    "Student",
    "Agriculture/Forestry/Fishing",
    "Art/Design/Media",
    "Banking/Finance/Real Estate",
    "Business/Sales/Office",
    "Construction/Energy Trades",
    "Education/Library",
    "Engineer/Architect/Science/Math",
    "Government/Military",
    "Information Technology",
    "Insurance",
    "Legal/Law Enforcement/Security",
    "Maintenance/Repair/Housekeeping",
    "Manufacturing/Production",
    "Medical/Social Services/Religion",
    "Personal Care/Service",
    "Restaurant/Hotel Services",
    "Sports/Recreation",
    "Travel/Transportation/Warehousing",
    "Other"
  ],
  "Occupation Title": [
    "Accountant/Auditor",
    "Actuarial Clerk",
    "Actuary",
    "Administrative Assistant",
    "Agent/Broker",
    "Analyst",
    "Attorney",
    "Claims Adjuster",
    "Clerk",
    "Commissioner",
    "Customer Service Representative",
    "Director/Administrator",
    "Executive",
    "Other",
    "Product Manager",
    "Receptionist/Secretary",
    "Sales Representative",
    "Underwriter"
  ],
  "DL Status (2)": [
    "Valid",
    "Permit",
    "Expired",
    "Suspended",
    "Cancelled",
    "Permanently Revoked"
  ],
  "Age Licensed": [
    "16",
    "17",
    "18",
    "19",
    "20",
    "21+"
  ],
  "License Sus/Rev (Last 5 years)": [
    "Yes",
    "No"
  ],
  "SR-22 Required": [
    "Yes",
    "No"
  ],
  "FR-44 Required": [
    "Yes",
    "No"
  ],
  "Driver Education": [
    "Yes",
    "No"
  ],
  "Mature Driver": [
    "Yes",
    "No"
  ],
  "Good Driver": [
    "Yes",
    "No"
  ],
  "Policy Type": [
    "Standard",
    "NonOwners",
    "BroadForm"
  ],
  "questionModel": [
    "No",
    "Yes"
  ],
  "No": [
    "No",
    "Yes"
  ],
  "Policy/Form Type": [
    "HO3 - Dwelling",
    "HO4 - Renters",
    "HO5",
    "HO6 - Condo"
  ],
  "Prior Carrier (2)": [
    "Other Standard",
    "Other Non-Standard",
    "No Prior Insurance",
    "21st Century",
    "AAA",
    "AAANCNU",
    "AARP",
    "Access Home Insurance Company",
    "Acuity",
    "Adirondack Ins Exchange",
    "Aegis",
    "AIG",
    "Alfa Alliance",
    "Allegany Co-op Insurance Company",
    "Allianz of America",
    "Allianz of America-Jefferson",
    "Allied Trust",
    "Allied",
    "Allmerica",
    "Allstate",
    "America First",
    "American Commerce",
    "American Family",
    "American Freedom Insurance Company",
    "American Integrity",
    "American Risk Insurance",
    "American Traditions",
    "Amica",
    "AmShield",
    "Anchor Insurance",
    "Andover Companies",
    "ASI Lloyds",
    "Atlantic Mutual",
    "Atlas General Agency",
    "Austin Mutual",
    "Auto-Owners",
    "Avatar Property and Casualty Insurance",
    "Badger Mutual Insurance Company",
    "Badger Mutual",
    "Balboa",
    "Bamboo Insurance",
    "Bankers",
    "Beacon National",
    "Bear River Mutual",
    "Berkshire Hathaway GUARD",
    "Brethren Mutual Insurance Company",
    "Bunker Hill",
    "Cabrillo Coastal",
    "California Casualty",
    "Capital Insurance Group",
    "Capitol Preferred",
    "Celina",
    "Centauri",
    "Central Mutual of OH",
    "Century National",
    "Chautauqua Patrons Insurance Company",
    "Chubb",
    "Cincinnati Casualty",
    "Cincinnati Insurance",
    "Citizens",
    "CNA",
    "Colorado Casualty",
    "Commonwealth",
    "Community Mutual",
    "Concord Group Insurance",
    "Consumers Insurance",
    "Countryway Insurance Co",
    "CSE",
    "Cumberland",
    "Cypress",
    "Dairyland",
    "Delta Lloyds Insurance Company",
    "Donegal",
    "Edison Insurance Company",
    "Electric",
    "EMC",
    "Encompass",
    "Encova Exceed",
    "Enumclaw Insurance",
    "Erie",
    "Esurance",
    "Excelsior Insurance Company",
    "Fair Plan",
    "Farm Bureau",
    "Farmers of Salem",
    "Farmers",
    "Farmers Fire Insurance Company",
    "FedNat Insurance Company",
    "Fidelity",
    "Firemans Fund",
    "First American",
    "Flagship Insurance",
    "Florida Family",
    "Florida Peninsula",
    "Florida Specialty",
    "Foremost Insurance Company",
    "Frankenmuth Mutual Insurance Company",
    "Fremont Insurance",
    "Frontline Insurance",
    "Geico",
    "General Casualty",
    "Germantown Mutual",
    "Germania Insurance",
    "GMAC",
    "Goodville Mutual",
    "Grange",
    "GRE/Go America",
    "Great American",
    "Grinnell",
    "Guide One",
    "GulfStream",
    "Hallmark Insurance Company",
    "Hanover",
    "Harleysville",
    "Hartford OMNI",
    "Hartford",
    "Hastings Mutual",
    "Hawkeye Security",
    "Heritage P/C",
    "Hippo Insurance",
    "Hochheim Prairie Insurance",
    "Homeowners of America",
    "Horace Mann",
    "Houston General",
    "Imperial Fire and Casualty Insurance",
    "Indiana Farmers",
    "Indiana",
    "Insurors Indemnity",
    "Integon",
    "Integrity",
    "Interboro Insurance Company",
    "Kemper",
    "LeMars Insurance",
    "Lemonade",
    "Liberty Mutual",
    "Liberty Northwest",
    "LightHouse",
    "Lititz Mutual",
    "Livingston Mutual Insurance Company",
    "Lloyds",
    "Madison Mutual Insurance Company",
    "Maidstone Insurance Company",
    "Main Street America",
    "Maison Insurance",
    "MAPFRE",
    "MAX - MutualAid eXchange",
    "Merchants Group",
    "Mercury",
    "MetLife",
    "Michigan Insurance Company",
    "Michigan Millers Mutual Insurance Company",
    "Midwestern Indemnity",
    "MissionSelect Insurance Services",
    "MMG Insurance Company",
    "Modern USA",
    "Monarch National Ins Co",
    "Montgomery",
    "Motorists Mutual",
    "MSA",
    "Mutual Benefit",
    "Mutual of Enumclaw",
    "National General One Choice",
    "National Lloyds Insurance Company",
    "Nationwide",
    "Nationwide-Scottsdale",
    "New York Central Mutual",
    "NJ Skylands",
    "NLC Insurance Companies",
    "Norfolk and Dedham Group",
    "Northern Neck Insurance Company",
    "Northstar",
    "Ohio Casualty",
    "Ohio Mutual",
    "Olympus Insurance Company",
    "Omaha P/C",
    "One Beacon",
    "Openly Inc",
    "Oregon Mutual",
    "Pacific Specialty Insurance Company",
    "Pacific Specialty",
    "Patriot Insurance",
    "Patrons Oxford",
    "Peerless",
    "Peerless/Montgomery",
    "Pekin",
    "PEMCO Insurance",
    "Peninsula Insurance Companies",
    "Penn National",
    "Pioneer State Mutual",
    "Plymouth Rock",
    "Preferred Mutual",
    "Prepared Insurance Company",
    "Progressive",
    "Providence Mutual Fire Insurance Company",
    "Prudential",
    "QBE",
    "Quincy Mutual",
    "RAM Mutual Insurance Company",
    "Republic",
    "Rockford Mutual",
    "Rockingham Casualty Company",
    "Royal and Sun Alliance",
    "Safeco",
    "Safepoint Insurance",
    "Safety Insurance Company",
    "SageSure Insurance Managers",
    "SECURA",
    "Selective",
    "Service Insurance Company",
    "Sheboygan Falls Insurance",
    "Shelter Insurance",
    "Southern Fidelity P/C",
    "Southern Fidelity",
    "Southern Mutual",
    "Southern Oak Insurance Company",
    "Southern Trust",
    "St. Johns",
    "St. Paul/Travelers",
    "Standard Mutual",
    "State Auto",
    "State Farm",
    "Sterling Insurance Company",
    "Stillwater Property and Casualty",
    "Stonegate Insurance",
    "Sublimity Insurance Company",
    "The Philadelphia Contributionship XML",
    "Titan",
    "Tower",
    "Towerhill",
    "Travelers",
    "TWFG",
    "TWICO",
    "Unigard",
    "Union Mutual",
    "United Fire and Casualty",
    "United Heritage Property and Casualty Company",
    "United Home",
    "United Insurance Group",
    "Unitrin",
    "Universal North America",
    "Universal Property and Casualty Insurance Company",
    "Universal",
    "Universal/Arrowhead Insurance company",
    "UPCIC",
    "USAA",
    "Utica First Insurance Company",
    "Utica National Insurance",
    "Utica National",
    "Velocity Risk Underwriters LLC",
    "Velocity Risk Underwriters Personal Lines",
    "Vermont Mutual",
    "Wayne Mutual Insurance Company",
    "Wellington Select",
    "Wellington Standard",
    "West Bend",
    "Western National",
    "Western Reserve Group",
    "Westfield",
    "Weston Specialty",
    "White Mountains",
    "Wilson Mutual",
    "Windsor",
    "Wisconsin Mutual Insurance Company",
    "Zurich"
  ],
  "Quote as Package": [
    "Yes",
    "No"
  ],
  "None": [
    "1",
    "2",
    "3"
  ],
  "questionModel (2)": [
    "Greater than $300,000",
    "$300,000",
    "Less than $300,000",
    "First Time Home Buyer",
    "Lapse in Coverage (30 days or less)",
    "No Prior or Lapse Greater Than 30 Days"
  ],
  "Mortgage Billed": [
    "Mortgage Billed",
    "Insured Full Pay",
    "Insured Pay Plan"
  ],
  "questionModel (2) (2)": [
    "No",
    "Yes"
  ],
  "Dwelling Usage": [
    "Primary",
    "Secondary",
    "Seasonal",
    "Farm",
    "COC"
  ],
  "Occupancy Type": [
    "Owner Occupied",
    "Renter Occupied",
    "Unoccupied",
    "Vacant"
  ],
  "Dwelling Type": [
    "One Family",
    "Two Family",
    "Three Family",
    "Four Family"
  ],
  "Number of Occupants": [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9 or more"
  ],
  "Number of Stories": [
    "1",
    "1.5",
    "2",
    "2.5",
    "3",
    "3.5",
    "4",
    "Bi-Level",
    "Tri-Level"
  ],
  "Construction Style": [
    "Apartment",
    "Backsplit",
    "Bi-Level",
    "Bi-Level/Row Center",
    "Bi-Level/Row End",
    "Bungalow",
    "Cape Cod",
    "Colonial",
    "Condo",
    "Coop",
    "Contemporary",
    "Cottage",
    "Dwelling",
    "Federal Colonial",
    "Mediterranean",
    "Ornate Victorian",
    "Queen Anne",
    "Raised Ranch",
    "Rambler",
    "Ranch",
    "Rowhouse",
    "Rowhouse Center",
    "Rowhouse End",
    "Southwest Adobe",
    "Split Foyer",
    "Split Level",
    "Substandard",
    "Townhouse",
    "Townhouse Center",
    "Townhouse End",
    "Tri-Level",
    "Tri-Level Center",
    "Victorian"
  ],
  "Roof Type (main material)": [
    "Architectural Shingles",
    "Asbestos",
    "Asphalt Shingles",
    "Composition",
    "Copper(flat)",
    "Copper(pitched)",
    "Corrugated Steel(flat)",
    "Corrugated Steel(pitched)",
    "Fiberglass",
    "Foam",
    "Gravel",
    "Metal(flat)",
    "Metal(pitched)",
    "Mineral Fiber Shake",
    "Other",
    "Plastic(flat)",
    "Plastic(pitched)",
    "Rock",
    "Rolled Paper(flat)",
    "Rolled Paper(pitched)",
    "Rubber Flat",
    "Rubber(pitched)",
    "Slate",
    "Solar",
    "Thatch",
    "Tar",
    "Tar And Gravel",
    "Tile(clay)",
    "Tile(concrete)",
    "Tile(spanish)",
    "Tin(flat)",
    "Tin(pitched)",
    "Wood Fiberglass Shingles",
    "Wood Shake",
    "Wood Shingles"
  ],
  "Foundation Type": [
    "Basement - Finished",
    "Basement - Partially Finished",
    "Basement - Unfinished",
    "Basement - Walkout",
    "Crawl Space - Enclosed",
    "Crawl Space - Open",
    "Daylight Basement - Finished",
    "Daylight Basement - Partially Finished",
    "Daylight Basement - Unfinished",
    "Hillside Foundation",
    "Other",
    "Piers",
    "Pilings/stilts",
    "Slab"
  ],
  "Roof Design": [
    "Dormer",
    "Flat",
    "Gable",
    "Gambrel",
    "Hip",
    "Mansard",
    "Other",
    "Pyramid",
    "Shed",
    "Turret"
  ],
  "Exterior Walls": [
    "Adobe",
    "Aluminum/Vinyl",
    "Barn Plank",
    "Brick",
    "Brick on Block",
    "Brick on Block, Custom",
    "Brick Veneer",
    "Brick Veneer, Custom",
    "Cement Fiber Shingles",
    "Clapboard",
    "Concrete Decorative Block, Painted",
    "Ext Insul and Finish Sys (EIFS)",
    "Fire Resistant",
    "Logs",
    "Poured Concrete",
    "Siding, Aluminum",
    "Siding, Hardboard",
    "Siding, Plywood",
    "Siding, Steel",
    "Siding, T-111",
    "Siding, Vinyl",
    "Siding, Wood",
    "Slump Block",
    "Solid Brick",
    "Solid Brick, Custom",
    "Solid Brownstone",
    "Solid Stone",
    "Solid Stone, Custom",
    "Stone on Block",
    "Stone on Block, Custom Stone",
    "Stone Veneer",
    "Stone Veneer, Custom",
    "Stucco",
    "Stucco on Block",
    "Stucco on Frame",
    "Victorian Scalloped Shakes",
    "Window Wall",
    "Wood Shakes"
  ],
  "Number Of Full Baths": [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10+"
  ],
  "Number Of Half Baths": [
    "1",
    "2",
    "3",
    "4",
    "5+"
  ],
  "# of Wood Burning Stoves": [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20"
  ],
  "Heating Type": [
    "Electric",
    "Gas",
    "Gas - Forced Air",
    "Gas - Hot Water",
    "Oil",
    "Oil - Forced Air",
    "Oil - Hot Water",
    "Other",
    "Other - Forced Air",
    "Other - Hot Water",
    "Solid Fuel"
  ],
  "Secondary Heating Source Type": [
    "Coal Non-Professionally Installed",
    "Coal Professionally Installed",
    "Electric Portable Heater",
    "Electric",
    "Kerosene Portable Heater",
    "Kerosene",
    "Liquid Propane Portable Heater",
    "Liquid Propane",
    "Natural Gas",
    "Oil",
    "Other",
    "Solar Non-Professionally Installed",
    "Solar Professionally Installed",
    "Wood Non-Professionally Installed",
    "Wood Professionally Installed"
  ],
  "Burglar Alarm": [
    "Central",
    "Direct",
    "Local"
  ],
  "Fire Detection": [
    "Central",
    "Direct",
    "Local"
  ],
  "Sprinkler System": [
    "Partial",
    "Full"
  ],
  "Smoke Detector": [
    "Central",
    "Direct",
    "Local"
  ],
  "Feet From Hydrant": [
    "1-500",
    "501-600",
    "601-1000",
    "1001-1100",
    "1101-1200",
    "1201-1300",
    "1301-1400",
    "1401-1500",
    "1501 and Greater",
    "None in Area"
  ],
  "Distance To Tidal Water(miles)": [
    "0-.5",
    ".5-1",
    "1-2",
    "2-5",
    "more than 5"
  ],
  "Protection class": [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10"
  ],
  "Heating Update": [
    "Not Updated",
    "Partial Update",
    "Complete Update"
  ],
  "Electrical Update": [
    "Not Updated",
    "Partial Update",
    "Complete Update"
  ],
  "Plumbing Update": [
    "Not Updated",
    "Partial Update",
    "Complete Update"
  ],
  "Roofing Update": [
    "Not Updated",
    "Partial Update",
    "Complete Update"
  ],
  "questionModel (3)": [
    "Progressive Auto 250/500",
    "Progressive Auto 100/300",
    "Progressive Auto 50/100",
    "Progressive Auto Less than 50/100",
    "Flood"
  ],
  "None (2)": [
    "Class 1",
    "Class 2",
    "Class 3",
    "Class 4"
  ],
  "NO": [
    "NO",
    "YES"
  ],
  "Personal Liability": [
    "25000",
    "50000",
    "100000",
    "200000",
    "300000",
    "400000",
    "500000",
    "1000000"
  ],
  "Medical Payments": [
    "1000",
    "2000",
    "3000",
    "4000",
    "5000"
  ],
  "All Perils Deductible": [
    "1/2%",
    "1%",
    "100",
    "250",
    "500",
    "750",
    "1000",
    "1500",
    "2000",
    "2500",
    "3000",
    "4000",
    "5000"
  ],
  "Theft Deductible": [
    "500",
    "1500"
  ],
  "Wind Deductible": [
    "100",
    "250",
    "500",
    "1000",
    "1500",
    "2000",
    "2500",
    "5000",
    "10000",
    "1%",
    "2%",
    "3%",
    "4%",
    "5%"
  ],
  "Cov A Plus": [
    "Cov A Plus",
    "Ext Limits",
    "Repl Cost"
  ],
  "Increased Replacement Cost Dwelling Percentage": [
    "125",
    "150",
    "200"
  ],
  "Loss Assessment": [
    "5000",
    "10000",
    "25000",
    "50000",
    "75000",
    "100000"
  ],
  "Ordinance or Law": [
    "10",
    "25",
    "50",
    "75",
    "100"
  ],
  "Increased Coverage on Credit Card": [
    "1,000",
    "2,500",
    "5,000",
    "7,500",
    "10,000"
  ],
  "Increased Limit on Jewelry,Watches and Furs": [
    "2500",
    "3000",
    "4000",
    "5000"
  ],
  "Water Backup": [
    "1000",
    "2000",
    "3000",
    "4000",
    "5000",
    "6000",
    "7000",
    "8000",
    "9000",
    "10000",
    "15000",
    "20000",
    "25000",
    "50000"
  ],
  "Increased Mold Property Damage": [
    "25000",
    "50000",
    "75000",
    "100000"
  ],
  "Earthquake Zone": [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9"
  ],
  "Deductible": [
    "5%",
    "10%",
    "15%",
    "20%",
    "25%"
  ],
  "None (3)": [
    "HomeShield Package",
    "HomeShield Plus Package",
    "Platinum Package"
  ],
  "Essential": [
    "Essential",
    "NewQualityPlus",
    "Optimum"
  ],
  "None (2) (2)": [
    "$25,000",
    "$50,000",
    "$100,000"
  ],
  "New": [
    "New",
    "Renewal",
    "Assigned",
    "Quoted/Active",
    "Price not competitive",
    "Pending Sale",
    "Proposed",
    "Campaign Email",
    "Campaign Phone",
    "Refused",
    "Responded",
    "Sold",
    "Future Prospect",
    "Bad Lead",
    "Ineligible",
    "Dead Lead",
    "Duplicate"
  ],
  "Contact Method (2)": [
    "Mobile Phone"
  ],
  "Contact Time": [
    "Morning",
    "Afternoon",
    "Evening",
    "Anytime"
  ],
  "Year": [
    "2026",
    "2025",
    "2024",
    "2023",
    "2022",
    "2021",
    "2020",
    "2019",
    "2018",
    "2017",
    "2016",
    "2015",
    "2014",
    "2013",
    "2012",
    "2011",
    "2010",
    "2009",
    "2008",
    "2007",
    "2006",
    "2005",
    "2004",
    "2003",
    "2002",
    "2001",
    "2000",
    "1999",
    "1998",
    "1997",
    "1996",
    "1995",
    "1994",
    "1993",
    "1992",
    "1991",
    "1990",
    "1989",
    "1988",
    "1987",
    "1986",
    "1985",
    "1984",
    "1983",
    "1982",
    "1981",
    "1980",
    "1979",
    "1978",
    "1977",
    "1976",
    "1975",
    "1974",
    "1973",
    "1972",
    "1971",
    "1970",
    "1969",
    "1968",
    "1967",
    "1966"
  ],
  "Passive Restraints": [
    "Automatic Seatbelts",
    "Airbag (Drvr Side)",
    "Auto Stbelts/Drvr Airbag",
    "Airbag Both Sides",
    "Auto Stbelts/Airbag Both"
  ],
  "Anti-Lock Brakes": [
    "Yes",
    "No"
  ],
  "Daytime Running Lights": [
    "Yes",
    "No"
  ],
  "Anti-Theft": [
    "Active",
    "Alarm Only",
    "Passive",
    "Vehicle Recovery System",
    "Both Active and Passive",
    "VIN# Etching"
  ],
  "Vehicle Use": [
    "Business",
    "Farming",
    "Pleasure",
    "To/From Work",
    "To/From School"
  ],
  "Performance": [
    "Standard",
    "Sports",
    "Intermediate",
    "High Performance"
  ],
  "Was the car new?": [
    "Yes",
    "No"
  ],
  "Ownership Type": [
    "Owned",
    "Leased",
    "Lien"
  ],
  "Car Pool": [
    "Yes",
    "No"
  ],
  "Telematics": [
    "Yes",
    "No"
  ],
  "Transportation Network Company": [
    "Yes",
    "No"
  ],
  "Bodily Injury": [
    "State Minimum",
    "25/50",
    "50/50",
    "50/100",
    "100/100",
    "100/300",
    "250/500",
    "300/300",
    "500/500",
    "1000/1000",
    "55 CSL -or- 50/50/50",
    "100 CSL -or- 100/100/100",
    "300 CSL -or- 300/300/250",
    "500 CSL -or- 500/500/500"
  ],
  "Property Damage": [
    "State Minimum",
    "10000",
    "15000",
    "25000",
    "50000",
    "100000",
    "250000",
    "500000"
  ],
  "Medical Payments (2)": [
    "500",
    "1000",
    "2000",
    "2500",
    "5000",
    "10000",
    "15000",
    "25000",
    "50000",
    "100000"
  ],
  "Uninsured Motorist Property Damage": [
    "No Coverage",
    "State Minimum",
    "10000",
    "15000",
    "25000",
    "50000",
    "100000"
  ],
  "Residence is": [
    "Home (owned)",
    "Condo (owned)",
    "Apartment",
    "Rental Home/Condo",
    "Mobile Home",
    "Live With Parents",
    "Other"
  ],
  "Comprehensive": [
    "No Coverage",
    "0",
    "50",
    "100",
    "200",
    "250",
    "500",
    "1000",
    "2000",
    "2500"
  ],
  "Collision": [
    "No Coverage",
    "0",
    "50",
    "100",
    "200",
    "250",
    "500",
    "1000",
    "2000",
    "2500"
  ],
  "Reject": [
    "Reject",
    "$100",
    "$200",
    "$300",
    "$400",
    "$500",
    "$600",
    "$700",
    "$800",
    "$900",
    "$1000",
    "$1100",
    "$1200",
    "$1300",
    "$1400",
    "$1500",
    "$1600",
    "$1700",
    "$1800",
    "$1900",
    "$2000",
    "$2100",
    "$2200",
    "$2300",
    "$2400",
    "$2500",
    "$2600",
    "$2700",
    "$2800",
    "$2900",
    "$3000"
  ],
  "None (4)": [
    "Insured/Spouse",
    "Extended Family"
  ],
  "Combo Auto": [
    "Combo Auto",
    "GrandProtect Auto"
  ],
  "No Coverage": [
    "No Coverage",
    "10000",
    "25000",
    "50000"
  ]
};
